### ISSUE TITLE
Enable form author to specify which sections are open when the form loads

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1448]
Right now, all the sections are open by default, but in some cases it might make sense to have some of the sections closed by default, and hence to let the form author author control which one.

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/4157621/messages/45163499)

**Comment by ebruchez** [comment]
UI: checkbox in Section/Grid Settings to select whether the section is open or closed by default. The default is that the section is open.

This setting must not be available to grids.

Should we also use the opportunity to have a setting to set the `collapsible` attribute on the section?

**Comment by ebruchez** [comment]
Since `collapsible` is also controlled by a property, we should either:

- have a 3-state option: "Default (from Properties)", "Collapsible", "Not collapsible"
- OR, since the main use case would be to prevent a section from collapsing (say the first section on the form), have the option say "Never Collapse".

If "Never Collapse" is selected, then "Initially Open" must be forced.
