### ISSUE TITLE
Publish on home page to take versions into account

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1451]
With the persistence API support for versioning (#1157) implemented, publishing forms from the [home page](both from local to remote, or remote to local), creates a new version on the "other side". This is most likely not the expected behavior. Instead, a reasonable behavior would be to copy, and possibly overwrite/delete, all versions.

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/2789956/messages/25095107#comment_359345547) to publish and update the last version.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/10553000/messages/1595589323)

**Comment by ebruchez** [comment]
This goes with #3448.

We fixed the version for the form definition upgrade with #2453, but making a form available/unavailable is wrong (#4476).

I suggest:

- showing all version in the Home page (#3448) as a separate column
- modifying all operations so that the selected form's version is used, including
    - making a form available/unavailable is wrong (#4476) (obviously)
    - pushing/pulling (we can make this more configurable in the future if needed)
- also check
    - reencrypt (does it depend on a version?)

**Comment by ebruchez** [comment]
This was implemented in March 2020 and released in Orbeon Forms 2021.1.
