### ISSUE TITLE
Versioning: support basic data migration

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1523]
As has been suggested, simply removing the fields that have been deleted and adding the field that have been added might be good enough as a first shot. This would not guarantee a perfectly good migration, but might be good enough for most scenarios. Some kind of user interaction to review the migration would be good to have.

**Comment by ebruchez** [comment]
+1 from me today for adding/removing fields. Would already cover quite a bit of ground.

**Comment by ebruchez** [comment]
What would the inputs of the migration process be? Probably:

- the old form definition
- the new form definition
- possibly, data associated with the old form definition

We don't have a access to the history of changes done by the user in Form Builder.

An obvious initial idea is to identify what's changed and not by looking at *control names only*.

For migration purposes, we can consider that the relative order of binds/data/controls within their container does not constitute an incompatible change. Migration could still update the order of elements.

What would the algorithm look like?

- easy case
    - bind hierarchy is the same (section names)
    - names added/removed within sections, maybe even moved between sections (not across repeats)
    - no validation/required changes
- harder cases
    - section added
    - section becomes repeated

If validation/required changes, there is the issue of whether the old data will be valid per the new validation rules.

What would a UI do?

- try to match if the migration follows an existing, handled scenario
- summarize the detected changes to the user
- if needed, ask the user whether to check the data too (e.g. to see if validation rules still apply)
- proceed to migrate only upon user confirmation

**Comment by ebruchez** [comment]
One question that was asked is: why do we store enclosing elements for (non-repeated) sections? That prevents moving controls between sections and keeping data that is compatible.

My current answer is that:

- the section information might be useful to some users
- data migration should take care of that anyway (see comment above)
- these elements are needed in the internal format for controlling visibility and readonly, and removing/adding them when writing/reading adds complexity (we already do some of that for repeated grids)

We might give a little bit more thought to the idea that maybe our data format in the database might not  need the enclosing section elements.

**Comment by ebruchez** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#search/quintiles/1538518756a40956)

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/2789956/messages/56013217) for a comparison feature telling the user what differences there are between the form definitions.

**Comment by ebruchez** [comment]
If we start by showing differences, what can we realistically do?

- structural changes
  - controls added/removed within sections, maybe even moved between sections
  - sections added/removed/moved
  - changes to/from repeated
- value changes
  - metadata changes: form title, etc. (also: i18n)
  - resources changes
  - other changes (min/max, etc.)

The value changes are easy to handle. The structural changes harder, because it gets down to a structural diff algorithm, and that's open-ended. But what we could do is start simple and handle the simple cases.

The diff would output a user-friendly list of changes in a Form Builder dialog.

**Comment by ebruchez** [comment]
Here is a [Java library](http://tree-edit-distance.dbresearch.uni-salzburg.at/) to compute tree edit distance. Their latest library implements very recent algorithms. It is called APTED and is under MIT license.

**Comment by ebruchez** [comment]
A first step would be the following:

- write simple form-to-bracket-notation-tree
- try out APTED to see what results it provides in terms of delete-insert-rename

**Comment by ebruchez** [comment]
Mmh, it seems that this APTED thing only produces a number, not a list of steps.

**Comment by ebruchez** [comment]
Our case is a little easier than a general-purpose tree diff because we have constraints:

- nesting only happens for sections and grids, where grids cannot contain any grids or sections
- while in theory infinite, in practice section nesting is limited to maybe 3 levels (and in most cases there will be 1 or 2 levels of sections)
- controls can be seen as a collection of attributes, including their name, LHHA, validations, etc., and they are always leaf items

As a first step we could, for each control, repeated grid, and section, compute a hash based on their properties. This is, BTW, what most tree diff algorithms start by doing anyway. This allows us to determine:

- whether form definitions are identical (except ordering of sections, grids and controls)
- whether there were simple additions/deletions of sections, grids and controls
- whether there were simple moves of sections, grids and controls

This would detect a change in, say, control name or label as an addition and deletion, which of course is not great. But it's a start, and reconciliation of differences between non-identical sections, grids and controls can follow.

**Comment by ebruchez** [comment]
Interestingly, all XML diff material is hopelessly out of date, but there is more hope if you all XML "DOM". For example [this](https://github.com/znerol/node-delta) seems reasonably current and also has a [paper](http://znerol.github.io/node-delta/).

**Comment by ebruchez** [comment]
And by "reasonably current", that meant 2012. Not great. And while the paper talks about handling moves as a post-processing step, their simple XML diff example online doesn't seem to show a move.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2010455/messages/1020312405)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/1232987402#__recording_1233045278)

**Comment by ebruchez** [comment]
For missing XML elements, we could add missing elements automatically without migrating the entire data in the database. How would this work?

1. One possibility: upon loading the form data, the static tree of controls is traversed and compared with the data. If the data is missing an XML element at a given level, it is automatically added.
2. Another possibility could be to produce migration information at form definition publish time: the previous form definition would be looked up, and local migration directives would be stored in the form definition, such as "add this element if missing". When loading data, the upgrade script would run.

**Comment by ebruchez** [comment]
Given a hierarchy of controls (either the form definition or another representation), it is easy to create an algorithm that goes through XML data and inserts missing elements.

**Comment by ebruchez** [comment]
Should there be modes/options when publishing and overriding, if the format just adds or even remove such as:

- do nothing (current behavior)
- show an error to the user if the data is incompatible
- migrate (add/remove elements)

**Comment by ebruchez** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#drafts/FMfcgxvxBXtHXwGMmHHqvgNnpclRDXfg)

**Comment by ebruchez** [comment]
- [ ] hook-up at the same spot we have `fr-get-document-submission` and `dataMaybeMigratedFromDatabaseFormat`
- [ ] use source of truth and iterate through it to identify missing elements compared to the data provided

What is the source of truth? We could look at:

- the data template before loading data
- binds

But there is also the question of section templates. In this case, the data template does not include any data at all, so we would need to go search for the data template in nested section template components. The same would go for binds.

**Comment by ebruchez** [comment]
For element templates, like for attachments:

```xml
<instance filename="" mediatype="" size=""/>
```

- we cannot use just the bind name, clearly
- we cannot look into the XBL template, because we are not in Form Builder and metadata is not available
- we cannot just look into the default instance, because for example  repeats might have 0 iterations

What we can do is look at a combination of the default instance AND  repeat templates.

**Comment by ebruchez** [comment]
Scenario for section templates:

- form definition with section templates published and data is created
- section template is modified to add fields
- form definition is republished to include new section template
- existing data is loaded with updated form definition

Now, instance data is handled differently with section templates:

- Data from bound instance is copied in.
- If data is missing in the bound instance upon `xforms-model-construct-done`:
    - The section template's `fr-form-template` is copied and then mirrored to the bound instance.
    - This case is ok, as `fr-form-template` is up to date`.
    - This should only happen in `new` mode.
- If data is present within the section template:
    - It was copied in from the bound instance.
    - It needs to be migrated if needed.

*NOTE: The migration map for grids handles section templates.*

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/features/versioning#simple-data-migration)
