### ISSUE TITLE
Actions: support selection controls with different itemsets in repeats

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1770]
Right now, we don't support different instances of the same selection control in a repeat being bound to different itemsets. This would be useful when doing cascading lists in repeats.

In some cases, as a workaround, it is possible to use a [data-bound select1], which works in repeats as it holds its itemset in its local model.

  [data-bound select1]: http://wiki.orbeon.com/forms/doc/developer-guide/xbl-components/databound-select1

**Comment by ebruchez** [comment]
Would be really good to address, but there doesn't seem to be urgent for 4.9.

**Comment by avernet** [comment]
[+1 from Twitter](https://twitter.com/s_andronikos/status/608649162335375361)

**Comment by acspike** [comment]
I got caught by this just this morning! Fortunately, I think I can work around the problem. Since my first selection has only 3 static options, I can make three dependent selections and appropriate visibility settings.

Are there any other work-arounds? Databound-select won't work for me because I'm using a database service.

**Comment by avernet** [comment]
@acspike There are no real workarounds, other than doing this with XForms code you write "by hand" and add to the form source.

**Comment by acspike** [comment]
Sounds unpalatable, but how is that done? Link?

**Comment by avernet** [comment]
To make sure I understand your situation well, are you saying that you have service and want the result to populate 3 different dropdowns, and this with the same values returned by the service?

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/11350532/messages/52730912)

**Comment by ebruchez** [comment]
Further thoughts if the [above](#issuecomment-66860849) idea of using `setItemset()` works out.

Open questions:

- User needs a way to determine whether the action must set all itemsets in the repeat, or only a specific one (probably the "closest", like for a `setvalue`). Could be checkbox in action.
- Statement above saying "This would allow handling the current case without having to modify the form's resources instance." might not hold: if the itemset is shared, how does adding iterations work? And how do we handle the case where there are no iterations? We would still need an external location to place the itemset. If we really want to keep the resources readonly, we could create specific itemset instances in the form (automatically when we process actions).

Tasks:

- [ ] Implement #768 since we need support for `fr:dropdown`.
    - Q: Then how does `fr:dropdown` pass itemset to nested `xf:select1`? Need #1520?
- [ ] implement `setItemset()` on selection controls including XBL controls.
    - Decide priority if there is an inline itemset. Possibly, a call to `setItemset()` would cause the inline itemset to be ignored from then on (until the control is disabled).
- [ ] Implement option in UI.
- [ ] Implement action depending on option.

**Comment by avernet** [comment]
Regarding your first bullet point, I was thinking about this, and thinking we could do without such an option, and just implement the "closest" behavior we have now `setvalue`. It would break compatibility when the user wanted a value changed in one iteration to change all dropdowns in the repeat, but I can't think of a use case where this behavior would make sense. I.e. when would it make sense that the last change in any iteration impacts the itemset of all the controls in all iterations?

**Comment by ebruchez** [comment]
Ok I guess that makes sense. In general if the itemset is homogeneous across a repeat, it's going to be loaded upon page load, or as the result of an action outside of the repeat.

**Comment by ebruchez** [comment]
@avernet mentions a hypothetical use case where the selection control can become relevant/non-relevant. In which case, when becoming relevant, it also needs to get its itemset. So we would need to call the service to load items then, which is a bit cumbersome.

Can we find a more declarative way, based on the notion of datasource maybe? The itemset would be updated as needed, provided its dependencies are known.

**Comment by ebruchez** [comment]
Another possibility would be to store the itemsets in the data.

Benefits:

- makes it easy to associated an itemset with an iteration
- allows editing existing form data without itemsets changing below the users' feet

Drawbacks:

- need to find a place in the data to store itemset
    - can't just store below value element
- takes more space in the data

The form author can have control of whether to reload an itemset or not:

- "Form Load" and "On Creation Only": `new` mode, persist itemset.
- "Form Load" only: all modes, don't necessarily persist itemset when saving.

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/11350532/messages/52730912)

**Comment by ebruchez** [comment]
Open questions:

- where to store each itemset value at runtime (resources, data, XBL control)
- whether to persist itemsets between runs
- whether to push (action → service) or pull (more like Dynamic Data Dropdown)
- performance (calling many services vs. keeping itemsets around, related to persistence)
- whether a notion of "datasource" would help

**Comment by ebruchez** [comment]
We are considering persisting itemsets for two reasons:

1. __Logical reason.__ If we say that an action setting an itemset runs only upon another control's value change, then we should run that at other times (like when the form loads). One problem with bending that rule is that the set of items returned by the service/datasource might have changed in the meanwhile.
2. __Performance reason.__ If a forms has lots of selection controls with dynamic itemsets, performance can suffer a lot upon edit/view/pdf/email operations.

**Comment by ebruchez** [comment]
We discussed above the idea of an `setItemset()` function. We could also implement that with an event: `xxforms-update-itemset` which would take the itemset as property (in XML or JSON).

If we decide we must persist some itemsets, which is likely, we face a problem: where to store the itemset?

1. __On an attribute of the data holder.__ For example an `fr:itemset` attribute. The problem is that the itemset might be large and we might hit limitations of XML parsers or databases (e.g. Oracle). The benefit is that this does not require a significant change in the data model: 
2. __Within a nested element of the data holder.__ But because the selection control stores its value as a direct child, and due to XForms rules, we would also need to introduce a child element for the control value. This is a change in the data model, which has consequences for users of the data model (upon `save` and `send`, for example) and for the XML Schema Generator.
3. __Out of band in a separate element.__ For example an `fr:itemsets` element, or maybe `fr:serializations`, etc. At runtime, itemsets would be kept private to controls. But upon `save` or mode changes, the controls would be queried, their itemsets serialized and compressed, and stored under that element. Upon recreating the control tree, we would need a way to read back those itemsets. This is a bit tricky. It looks like the XForms engine's deserialization, except that we cannot fully trust ids in case the form layout or XBL components have changed a bit.
4. __Completely out of band.__ Like number 3 above, we could store the serialized information entirely out of band: send it via headers, and store it under `metadata.xml` vs. a separate column. This raises the same question of how to restore itemsets upon initializing controls again. (The proposed Stage information (#2256) would be stored completely off-band, but it's much smaller.)

**Comment by ebruchez** [comment]
If we go that way (indirection via id), we would not need an `xxforms-update-itemset` event. We could just:

1. Store the itemset in the data with a unique id.
2. Set the `fr:itemsetid` attribute referring to it.
3. Wait for the next refresh.

And voilà.

What about section templates? Services and actions are local to them, and their data is local too but mirrored. The result might be an ``fr:metadata>` element stored deeper in the XML hierarchy. Would this make sense?

Could this, or a variation, also be used for the case where we change all itemsets at the same time within a repeat? If the id is still specified within the data, we would need to:

1. store the single itemset within the data. It would be persisted as well as needed, which is correct.
2. set the *same itemset id* on all associated repeated elements.

Other changes:

- The Summary page should also use itemsets stored in the data when needed.
- The `send` action might need an option to trim this information by default for backward compatibility.
- Make sure this works with section templates.

**Comment by ebruchez** [comment]
If an itemset update is global, then maybe the repeat template should be updated with `xf:itemsetid` so that new iterations point to that itemset too.

But what if we are 2 level repeated, and the update is for all iterations of a single instance of the nested repeat?

**Comment by ebruchez** [comment]
Steps:

- [ ] implement `getItemset()` for selection controls which checks the bound node's `xxf:itemsetid`, resolves the indirection, and reads the itemset
    - maybe enter separate issue
    - need to define itemset format
- [ ] update `fr-itemset-action` implementation
    - extract itemset in multiple languages if needed
    - insert itemset into data
    - create appropriate `xxf:itemsetid` attributes
- [ ] handle section templates
- [ ] create option for `send`
    - make sure new/edit/view/pdf/email work as expected
    - what about POSTing XML to page?
- [ ] make sure we handle inserting new iterations for repeats whose itemsets were set "globally" (see issue in previous comment too)
- [ ] make form resources readonly again if we can (should be the case)
- [ ] check whether Summary page needs changes
- [ ] P2: optimize case where persisting the itemset is not needed ("run on form load always")

**Comment by ebruchez** [comment]
It would be good to be able to handle dependencies so the itemset is not constantly rebuilt. Maybe express the dependency via XPath, as if the itemset was the following expression:

```ruby
for $idref in ./@xxf:itemsetid/string() return
    string(id($idref))
```

or something along those lines (depending on the format of the itemset in the data). This would require:

- adding that dependency to all selection controls
- support for `id()` in `PathMapXPathAnalysis`
- update `PathMapXPathDependencies`

**Comment by ebruchez** [comment]
Thinking that we could simplify the implementation by moving the handling of the itemset-by-id to Form Builder, which would add the following to selection controls whose itemset is controlled by an action result:

```xml
<xf:itemset ref="id(@xxf:itemsetid)[1]/(choices[@xml:lang = xxf:lang()], choices)[1]/item">
    <xf:label ref="label"/>
    <xf:value ref="value"/>
</xf:itemset>
```

We also need to modify the static itemset in that case, to:

```xml
<xf:itemset ref="if (empty(@xxf:itemsetid)) then $form-resources/control-3/item else ()">
    <xf:label ref="label"/>
    <xf:value ref="value"/>
</xf:itemset>
```

This assumes the following itemset format:

```xml
<itemset id="fr1277069312">
    <choices xml:lang="en">
        <item>
            <name>...</name>
            <value>...</value>
        </item>
        <item>
            <name>...</name>
            <value>...</value>
        </item>
    </choices>
    <choices xml:lang="fr">
        <item>
            <name>...</name>
            <value>...</value>
        </item>
        <item>
            <name>...</name>
            <value>...</value>
        </item>
    </choices>
</itemset>
```

Benefits:

- no need to hardcode the itemset format
- no need to check "by-id" itemsets for all selection controls at runtime
- simpler implementation
- no changes to the XForms engine

Drawbacks:

- a bit more XForms markup in the source form

This would still require `id()` support for dependencies.

**Comment by ebruchez** [comment]
We need to answer the question of what happens to new repeat iterations. If we do nothing, new iterations all have the default, static itemset defined at design time.

This in particular is not compatible with the 4.10  behavior, where if you set an itemset, it is set globally. It not only is a backward compatibility issue: it is also a desirable thing to do in some cases, for example if an action loads itemsets globally upon form load.

One way to look at it would be to say: "if to reach the target from the source, we must take one repeat branch, then update the repeat template".

This would address the following use cases:

- source and target on the same line
- global load

This would not solve the use case of, say, a button within a repeated section, which sets controls in a nested repeated grid. The change would be global, not local to the current repeated iteration of the section.

In order to solve that, we would need a place to store information about the itemset for that specific repeat iteration. And we don't really have a way to store this right now, do we?

Thinking more about it, there is an issue with modifying repeat templates: they are not persisted! So if a global itemset is loaded, the itemset proper will be persisted, but not the repeat template. Upon save/load, the information would be lost. So we need to store *something* within the form data: either under `<fr:metadata>`, or somewhere else (e.g. associated with an iteration).

It also follows that, if `xxf:itemsetid` is not stored in the template, that some extra logic must set `xxf:itemsetid` after inserting a new repeat iteration.

**Comment by ebruchez** [comment]
Here would be a possible example, where we would set the itemset for the second `section-iteration`.

```xml
<form>
    <section>
        <section-iteration>
            <button/>
            <grid>
                <grid-iteration>
                    <number>11</number>
                    <my-selection/>
                </grid-iteration>
                <grid-iteration>
                    <number>12</number>
                    <my-selection/>
                </grid-iteration>
                <grid-iteration>
                    <number>13</number>
                    <my-selection/>
                </grid-iteration>
            </grid>
        </section-iteration>
        <section-iteration xxf:itemsetmap="my-selection=fr1913b8d35e">
            <button/>
            <grid>
                <grid-iteration>
                    <number>21</number>
                    <my-selection/>
                </grid-iteration>
                <grid-iteration>
                    <number>22</number>
                    <my-selection/>
                </grid-iteration>
                <grid-iteration>
                    <number>23</number>
                    <my-selection/>
                </grid-iteration>
            </grid>
        </section-iteration>
    </section>
</form>
```

If the itemset is instead global:

```xml
<form xxf:itemsetmap="my-selection=fr1913b8d35e">
    <section>
        <section-iteration>
            <button/>
            <grid>
                <grid-iteration>
                    <number>11</number>
                    <my-selection/>
                </grid-iteration>
                <grid-iteration>
                    <number>12</number>
                    <my-selection/>
                </grid-iteration>
                <grid-iteration>
                    <number>13</number>
                    <my-selection/>
                </grid-iteration>
            </grid>
        </section-iteration>
        <section-iteration>
            <button/>
            <grid>
                <grid-iteration>
                    <number>21</number>
                    <my-selection/>
                </grid-iteration>
                <grid-iteration>
                    <number>22</number>
                    <my-selection/>
                </grid-iteration>
                <grid-iteration>
                    <number>23</number>
                    <my-selection/>
                </grid-iteration>
            </grid>
        </section-iteration>
    </section>
</form>
```

The algorithm for `fr:grid` and `fr:section` would look like this:

Upon inserting a new iteration:

- search the ancestors of the insert context for `xxf:itemsetmap`
- create a resulting map `name → itemsetid`, where items closest from the context have the highest priority
- if not empty, update all corresponding element names in the template to insert to add the `xxf:itemsetid` attribute
- insert the modified template

The garbage collection algorithm upon action result must also be updated to take into account itemsets referred to by `xxf:itemsetmap` attributes.

**Comment by ebruchez** [comment]
RESOLUTION: We defer handling of backward compatibility because the old behavior was not useful as is and the probability that existing forms make use of that old behavior is low.

**Comment by ebruchez** [comment]
New discussion with [customer](https://3.basecamp.com/3600924/buckets/1978677/messages/300961991) on options not to always persist the metadata.
