### ISSUE TITLE
Don't require setting forward-submission-headers with owner/group-based permissions on eXist

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2061]
Right now, we require `<property as="xs:string"  name="oxf.xforms.forward-submission-headers" value="Orbeon-Username Orbeon-Roles Orbeon-Group"/>`, as [documented](https://github.com/orbeon/orbeon-forms/wiki/Form-Runner-~-Access-Control-~-Owner-Group), but this shouldn't be needed, and we should automatically forward those headers.

**Comment by avernet** [comment]
Setting headers as done in 9c261c41bac4babc48f03d7d60aaeeb26190df3a isn't enough, as unlike the [code handling forward-submission-headers](https://github.com/orbeon/orbeon-forms/blob/tag-release-4.8-ce/src/main/scala/org/orbeon/oxf/util/Connection.scala#L514), we're not taking into account the credentials. I think we should. This means that form authors would be able to access the username/role/group, but it doesn't look to me like this would be a security risk.

To discuss with @ebruchez, and for now reassigning as most likely a change for @ebruchez to implement.

**Comment by avernet** [comment]
If we had #2062 and #2063, we could also use those specialized functions, instead of relying on `xxf:get-request-header()`.

**Comment by ebruchez** [comment]
To clarify, here is what is meant to happen:

- independently from the auth method (`container|header`), OF sets the `Orbeon-Username`, etc. headers internally in any `ExternalContext.Request` (done in [`FormRunnerRequestFilter`](https://github.com/orbeon/orbeon-forms/blob/master/src/main/scala/org/orbeon/oxf/servlet/FormRunnerRequestFilter.scala))
- for the `header` method, this assumes that the headers to look at are present in the internal request
- the persistence proxy
  - also gets the `Orbeon-Username`, etc. headers this way
  - forwards all non-connection headers out (so including `Orbeon-Username`, etc. if they have been created)
- an external persistence layer would then receive those headers
- an internal persistence layer, like the eXist one, would
  - receive those headers
  - but overwrite them anyway with the same values as the request is internal, based on credentials/incoming headers

When using the `container` mode, things seem to work properly. That's because internal requests implement `getUserPrincipal` by delegating to the incoming request.

However, the `header` mode doesn't work, because internally we don't implicitly forward authentication headers specified by properties, and we don't forward `Orbeon-Username`, etc. either.

**Comment by ebruchez** [comment]
Proposed fix:

- `Request`
  - rename `getRemoteUser` to `getUsername` and map to `Orbeon-Username`
  - add `getUserGroup` and `getUserRoles` mapping to `Orbeon-Group` and `Orbeon-Roles`
- `LocalRequest`
  - delegates all these to the incoming request (as `getRemoteUser` does now)
  - creates `Orbeon-Username`, `Orbeon-Group` and `Orbeon-Roles` based on those

Keep in mind that we create the `Orbeon-Username`, `Orbeon-Group` and `Orbeon-Roles` headers only for incoming external requests. Internal requests until now didn't. So now we ensure:

- that `getUsername` is consistent with `Orbeon-Username`
- that whether the request is internal or external, the headers as well as the functions are set

**Comment by ebruchez** [comment]
Also handle `Request.isUserInRole()` for consistency.

**Comment by ebruchez** [comment]
Properly sending headers to eXist also required fixing #2144. This was not strictly needed as our queries don't currently require `Orbeon-Roles`, but sending only one role out of all roles was definitely incorrect.

The alternative would have been to not send `Orbeon-Roles` to eXist at all. But I think that it was better to fix `oxf:url-generator` whose behavior was confusing.
