### ISSUE TITLE
First labelHintEditor misplaced on scrolled page in Chrome

### ISSUE THREAD

**Issue by acspike** [orbeon/orbeon-forms#2093]
When using the Chrome browser, if I open a form definition in form builder, scroll the page and then click on a label, the labelHintEditor is misplaced. Everything functions fine and subsequent appearances of the labelHintEditor are correctly placed. The problem is that this is often the first thing people see when I am doing demos of Orbeon on campus and it gives Orbeon a little bit of a black eye. This does not happen with Firefox. It appears to me to be a jQuery bug. A simple but ugly work around is to set the offset a second time immediately.

```
diff --git a/src/resources/forms/orbeon/builder/resources/cell/control-resources-editor/actions.coffee b/src/resources/forms/orbeon/builder/resources/cell/control-resources-editor/actions.coffee
index 1d13585..cf1441d 100644
--- a/src/resources/forms/orbeon/builder/resources/cell/control-resources-editor/actions.coffee
+++ b/src/resources/forms/orbeon/builder/resources/cell/control-resources-editor/actions.coffee
@@ -67,6 +67,7 @@ Builder.resourceEditorStartEdit = () ->
     labelHintEditor().selectTextInput()
     labelHintEditor().container.show()
     labelHintEditor().container.offset(labelHintOffset)
+    labelHintEditor().container.offset(labelHintOffset)
     labelHintEditor().container.width(Builder.resourceEditorCurrentLabelHint.outerWidth())
     labelHintEditor().editControl.val(labelHintValue()).focus()
     labelHintEditor().checkbox.prop('checked', isLabelHintHtml())
```

I realize that this is a bit dirty. Is it worth a pull request?

**Comment by acspike** [comment]
There is a similar issue with the publish dialog jumping, but I haven't investigated to see if it stems from the same cause.

**Comment by acspike** [comment]
Any comment on the hackyness of the proposed fix? The code is rather straight forward. I can't imagine there is a bug in your use of jquery there. Do you prefer a work around like this or to investigate the upstream issue?

**Comment by avernet** [comment]
Aaron, I didn't get a chance to look at this one, but rally would like to as I also hit it a few times and it indeed doesn't look very "clean". I'm hoping to get to this before 4.9.

**Comment by avernet** [comment]
Indeed, this is a strange one. And it doesn't happen on Firefox, which makes me think that something funky is happening on Chrome. It looks like `.offset(coordinates)` leads to incorrect results when the block isn't visible at the time when `.offset(coordinates)` is called. But this isn't the case here: we are showing it before we position it.

I've found that if we set the initial top/left to 0, then offset works. Now, I'm not sure why. It is as if, Chrome didn't consider the block to be really visible, or gets confused as to its initial position with a top/left set.

Calling `.offset(coordinates)` twice worked as the first call has the effect of setting the top/left, so I went with setting them explicitly with CSS rather than calling `.offset(coordinates)` twice.
