### ISSUE TITLE
Number control to map to `xs:integer` in addition to `xs:decimal`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2187]
We want the number control to be used for all the number types the form authors chooses in Form Builder, not just *Decimal* (`xs:decimal`). For this, the `<xbl:binding element="…">` needs to support multiple types, e.g. `xf|input:xxf-type('xs:decimal'), xf|input:xxf-type('xs:integer'), …`.

[+1 from community](https://twitter.com/akail892/status/588794259047854080)

**Comment by ebruchez** [comment]
I just tried adding `xf|input:xxf-type('xs:integer')` to the XBL binding for `fr:number`, and things seem to go smoothly in Form Builder. Maybe it's the only thing to do?

**Comment by ebruchez** [comment]
BTW original [community](https://twitter.com/akail892/status/588794259047854080) request was for "non negative decimal". There is no such type in XForms, although there is `nonNegativeInteger`. Might have been typo, but asked for clarification anyway.

This said, we don't like the `nonNegativeInteger`, `nonPositiveInteger`, `negativeInteger`, and `positiveInteger` types, because they only apply to integer types. In fact in 4.10 they are removed from the list of datatypes unless already present in the form.

We think we would be better served by using only the plain `integer` type, and then applying restrictions on the type, such as `positive-or-zero`, `positive`, `negative-or-zero`, and `negative`, see #1112.

**Comment by ebruchez** [comment]
Answering my own question above (), the answer is no: the `fr:number` code assumes `xs:decimal`, with `$binding castable as xs:decimal` and `xs:decimal($binding)`. This will work for `xs:integer`, but not for all floating-point numbers. For example, `'1e5' castable as xs:decimal` returns `false()`.

**Comment by ebruchez** [comment]
And curiously, even `xs:integer` doesn't work out of the box. Enter "12.34" for example, and the field appears blank instead of showing the incorrect value to edit.

**Comment by avernet** [comment]
> We think we would be better served by using only the plain `integer` type, and then applying restrictions on the type, such as `positive-or-zero`, `positive`, `negative-or-zero`, and `negative`, see #1112.

Yes. And `integer` seems can be conflated into a "zero digits after the decimal" validation on a decimal.

**Comment by ebruchez** [comment]
BTW just implemented "Positive", "Positive or Zero", "Negative or Zero", "Negative", "Maximum Fractional Digits" (#2490).

**Comment by ebruchez** [comment]
Now it seems that binding the control to `xf:integer` or `xs:integer` works as expected, and for #2487 we can also test the binding on `xs:integer` instead of using `xs:decimal` with 0 fractional digits to trigger the keypad on iOS.

**Comment by ebruchez** [comment]
I don't think we care that much about `xs:double` at this point. So renaming the issue to address integers only, since that seems to work. If doubles are really needed at some point, enter another issue.
