### ISSUE TITLE
FR: Saving a zero byte attachment causes a 500 error

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2289]
A zero byte attachment can be uploaded, but when I try to save I get a 500 error:

ORA-01400: cannot insert NULL into ("ORBEON"."ORBEON_FORM_DATA_ATTACH"."FILE_CONTENT")

I wouldn't expect anyone to need a zero byte attachment, but this error should be prevented. I would recommend catching this at upload time since this is probably an indicator that something went wrong.

**Comment by ebruchez** [comment]
@ajw625 Did you get to that point because of an upload error, or because you attached an empty file?

It doesn't seem very useful to upload a zero-byte attachment but in theory it is possible to have an empty file and try to upload it. I think it might be good to allow empty attachments, and exclude them, if desired, via validation.

Certainly there shouldn't be an error when storing such an attachment.

**Comment by ajw625** [comment]
I uploaded a random file that just happened to be empty. I haven't experienced any upload errors.

Sure, that approach sounds reasonable.

**Comment by ebruchez** [comment]
It might just be a matter of making the `file_content` columns nullable instead of `NOT NULL`.

**Comment by ajw625** [comment]
Here's the sql:

    alter table orbeon_form_definition_attach modify (file_content null);
    alter table orbeon_form_data_attach modify (file_content null);

I ran those and they resolve the 500 error.

**Comment by ebruchez** [comment]
Tentatively assigning to @avernet for 4.10, if it's an easy fix.

**Comment by avernet** [comment]
Also tested that storing zero byte attachments works on MySQL, DB2, and SQLServer (as expected).
