### ISSUE TITLE
IE 8: JS error on client when entering text in text area

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2311]
- Controls form
- enter data in textarea with character counter

This doesn't happen with IE 9+ in native mode, but it does in IE8 mode with IE9+. The IE 11 debugger shows the issue but hangs in IE 8 mode after a click.

![debugger](https://cloud.githubusercontent.com/assets/105769/8662356/857b0de6-2973-11e5-9679-fbb3693ba6bb.png)

**Comment by avernet** [comment]
This is caused by IE8 not knowing about the HTML5 `output` element, producing a rather interesting DOM, and failing with `unexpected call to method or property access` when our JavaScript tries to set the value of this `output` element.

![IE8 DOM with output](http://i.imgur.com/jY1s5X9.png)

Fortunately, the [solution](http://tatiyants.com/how-to-get-ie8-to-support-html5-tags-and-web-fonts/) is simple: just adding the following to the `<head>`, before other scripts will get IE8 to treat `<output>` very much like a `<span>`:

```
<!--[if lt IE 9]>
    <script>
        document.createElement('output');
    </script>
<![endif]-->
```
