### ISSUE TITLE
Formatted Text width not adjusted when device is rotated

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2368]
I just tried out the responsive design on the demo site all fields shrink when I narrow the window except Formatted Text. I tested in Chrome and IE 11 with the same result.

http://demo.orbeon.com/orbeon/fr/orbeon/bookshelf/edit/5bba537614484bd9e33c97bfc7649889

![orbeon-formatted-text-doesnt-shrink](https://cloud.githubusercontent.com/assets/9143532/9610900/4240069a-5091-11e5-86f3-4d1ce33595d2.png)

**Comment by avernet** [comment]
The TinyMCE is sized when it becomes visible, and currently doesn't resize itself when the window size changes. So this typically won't happen on a mobile… unless you rotate the device, in which case the TinyMCE will either be too large (if you went from landscape to portrait) or too narrow (if you went from portrait to landscape). I've changed the issue description to reflect this.

**Comment by ajw625** [comment]
Thanks. I see if the browser window is narrow when the form is loaded then it looks fine.

**Comment by ebruchez** [comment]
Still an issue as of 4.11.

**Comment by GameDevZach** [comment]
Any ideas on how to make these responsive? I've noticed that the formatted text width also overflows out of the Bootstrap section (and off-screen) if you resize the browser down after initializing. One way to make a single row responsive is to use the slightly more explicit "vw" units (i.e. 60vw) instead of % for max-width of .mceLayout but that doesn't work out when you have more than one formatted text area on a row.

**Comment by ebruchez** [comment]
This appears fixed with the move to TinyMCE 4 (#1753). It resizes nicely when resizing the window on the desktop as well as when changing orientation on a phone. So I am closing this as the fix will be available in Orbeon Forms 2018.1.

I am not sure there is a good solution with the old TinyMCE but it appears that the component uses JavaScript to size itself, not just plain CSS.

**Comment by GameDevZach** [comment]
@ebruchez I found a solution for pre-2018.1 versions of Orbeon with CSS, combining the two methods works, using explicit units for the max seems to prioritize the css sizing over the Javascript:

```
.orbeon table.mceLayout{
    width: 100% !important;
    max-width: 80vw !important;
}
```

**Comment by ebruchez** [comment]
@GameDevZach Great, thanks for sharing!
