### ISSUE TITLE
Metadata in SQL can take more than 4000 characters

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2385]
When this happens, this causes an error.

The reason here is a long description. Is the description actually needed by users of the `metadata` column?

[+1 from customer](https://basecamp.com/1721271/projects/3412232/messages/37902166#comment_328764997)

**Comment by avernet** [comment]
[+1 from community](https://twitter.com/BankJovita/status/689815070310809600)

**Comment by avernet** [comment]
We introduced the `metadata` column in 4.6 mid-2014 for #1728, storing the content if the `fr-form-metadata` instance in a separate column. Before, we used to retrieve the whole form definition from the database, and extract the metadata in XSLT.

Possible solutions to this issue:

1. Use a `clob` instead of `varchar`. This has been considered, but reading from a clob is much slower than a varchar, by a factor of 30 in Erik's tests.
2. Use a larger `varchar`. The limit to 4000 is imposed by Oracle 11g and SQL Server, so this seems a no-go.
3. Pruning from the metadata information we don't need, in particular `<description>` and `<migration>` elements, both of which might get voluminous. This is done in `CreateUpdateDelete.scala` (look for `metadataFilter`).

Resolution: we'll got with the third option.
