### ISSUE TITLE
Email to support dynamic content

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2428]
We want emails to be able to support dynamic content just as the `fr:explanation` control will once  #2427 is implemented.

**Comment by acspike** [comment]
This would be very useful (particularly inserting control values in to email). I would love to hear what is necessary for this to happen.

**Comment by ebruchez** [comment]
Some tasks coming to mind:

- [ ] define the template format (should we do as #2427 suggests?)
- [ ] implement the template format, including resolving variables
- [ ] maybe we need an option to enable/disable template processing for backward compatibility
- [ ] maybe creating the email body should be possible directly from Form Builder (that would be new UI)

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/156580544dccf91f) to add the ability to embed a link pointing to the form data.

**Comment by acspike** [comment]
This morning I ran across a case where it would be very nice to include a link back to the form in the email.

**Comment by ebruchez** [comment]
@acspike Yes that would definitely be good.

**Comment by ebruchez** [comment]
[+1 from user](http://discuss.orbeon.com/Email-body-per-form-query-td4661929.html#a4661947)

**Comment by ebruchez** [comment]
See #3078 for defining a template format.

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/16132a065703e104)

**Comment by ebruchez** [comment]
The email subject should also use a template.

**Comment by avernet** [comment]
[+1 from user](https://mail.google.com/mail/u/0/#inbox/162b15cb1bd5cffd)

**Comment by ebruchez** [comment]
As a first step, can we support the limited format which we have for dynamic LHH (see #1342)? That format calls for a template which contains names, as well as a separate mapping of those names to control values or XPath expressions. This split was done for i18n reasons, which also apply to email templates.

In order to handle this, we would need the ability to create an email template in Form Builder, probably, at least for the parameter parts. A format entirely defined in properties would be too cumbersome.

Currently, `email-form.x(p|s)l` doesn't run the form. `fr-email-subject` extracts values directly from the data holders. Can we use this as well for our template format? For control values, we can easily extract them from the data, but if we want to support XPath expressions, then what environment needs to be available? Many functions which assume the form environment wouldn't work. As a first step, we could just allow for control values?

**Comment by ebruchez** [comment]
Now let's say we have the template system in place, how could we extend that to the ability to output automatically all control values? Just a template like:

```
{$foo}
```

and then a new option (in addition to control value and XPath expression) to automatically include all controls?

**Comment by ebruchez** [comment]
Thinking that:

- We add an "Email Settings" dialog to Form Builder.
- This allows editing template and parameters.
  - The template can be localized.
- The template is optional and if missing, templates defined in properties are used.
  - This allows for setting global templates, like "Hi, here is your form data. {$data} Thanks!".

**Comment by ebruchez** [comment]
Other considerations:

- Currently, email template property is a resource override; need to decide how to handle that for backward compatibility.
- Since we are doing the email body, we should also do the email subject.
- Make sure that we can identify non-relevant fields. They are annotated now.

**Comment by ebruchez** [comment]
Consolidated list of tasks:

- [x] define the template format #3078
- [x] implement the template format, including resolving variables
- [ ] We add an "Email Settings" dialog to Form Builder.
  - [ ] editing template and parameters
  - [ ] optional template
  - [ ] specify email body
  - [ ] specify email subject
  - [ ] template can be localized
- [ ] runtime
  - [ ] if missing, templates defined in properties are used
    - This allows for setting global templates, like "Hi, here is your form data. {$data} Thanks!".
  - [ ] make sure that we can identify non-relevant fields (they are annotated now)
  - [ ] Currently, email template property is a resource override; need to decide how to handle that for backward compatibility.
- [ ] maybe we need an option to enable/disable template processing for backward compatibility

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/FMfcgxmZVPXJCRntGfrrlWjssWrkGGrM)

**Comment by ebruchez** [comment]
Moving to 2018.1 as this is in progress for a customer.

**Comment by ebruchez** [comment]
How should `fr:relevant-form-values()` extract all control values?

We have `FormRunnerMetadata` which produces the `metadata` XML output, which does something similar. It relies on using `XFormsAPI.inScopeContainingDocument`.

In our case, the email is sent through a service. However, this service is an internal service, and we do not document it to the outside world. This means that `XFormsAPI.inScopeContainingDocument` should still work within the service.

Whether this should be done like this is arguable, but if we look, in this case, at the use of a service purely because we decided to implement the email function using XPL, then it is fine. We had the same question with #3562 about where to evaluate what (in that case it was attachment filenames). If we want at some point to provide sending emails from the Summary page then we'll need to revisit this.

So suggesting we base the work on `FormRunnerMetadata` and reuse code if possible.

**Comment by ebruchez** [comment]
- [ ] `fr:relevant-form-values()`
  - [ ] base on `FormRunnerMetadata`
  - [ ] formatted values
  - [ ] selection controls labels
  - [ ] dynamic selection controls: get item values from embedded itemset
  - [ ] don't include non-relevant controls

**Comment by ebruchez** [comment]
Hitting again the distinction between  the `$mode = 'controls'`  vs. `send(content = "metadata")` distinction which I keep forgetting:

- `$mode = 'controls'`: lower-level XForms feature
- `send(content = "metadata")`: higher-level Form Runner feature

Here we are looking for the higher-level feature.

**Comment by ebruchez** [comment]
There are some difficulties with obtaining formatted values of all the controls. So far, we have the following ways to do that in our code:

- static readonly mode (for `view`/`pdf`)
  - *handlers* and XBL components output their formatted values
- PDF templates
  - done with ad-hoc XPath expressions operating on the HTML

The controls proper have a concept of *external value*, but that is not consistently used. For example, an `xf|input:xxf-type('xf:date')` sends Ajax updates to the client using unformatted values, like `2018-06-06`. This might make sense (?), as for example the client currently needs a date/time split into components (although the component should be an XBL component anyway).

XBL controls don't have a declarative way to expose formatted values, which we would need to properly handle the JavaScript lifecycle (which came up in #1117 recently as well).

**Comment by ebruchez** [comment]
For now, we could format according to the datatype: always format dates the same way, etc. This would take care of built-in controls and XBL controls for those types.

**Comment by ebruchez** [comment]
What `evaluateExternalValue` returns for all controls:

- `XFormsValueComponentControl`
  - if `external-value` mode, then `getValue`
  - otherwise, `null`
- `XFormsUploadControl`: `null`
- `XFormsSelect1Control`: TODO
- `XXFormsAttributeControl`: TODO
- `XFormsOutputControl`: TODO
- `XFormsRangeControl`: TODO
- `XFormsInputControl`: TODO
- `XFormsSelect1Control`: TODO

**Comment by ebruchez** [comment]
For templates, like for dynamic LHHA, we need:

- email template, which can be different per language
  - stored under `<metadata>`
  - also available via a property
  - Q: Should we default to the `email.subject` and `email.body` resource properties?
- template parameters, which do not change per language

It seems that we do need to have a UI even in a first phase, at least to set the parameters.

**Comment by ebruchez** [comment]
A question arises as to how to represent values of checkboxes, in particular. In the `view` mode, we output a something-separated list of labels. But in the email, because the structure is less apparent, this is harder to understand. If there is a single checkbox, or checkbox labels with for example  numbers like "1. This thing", it is confusing.

So we should show those better. A suggestion would be to use [x] (or ☒) when selected, and [ ] (or ☐) when deselected. The values could be indented below the label of the control.

Now when should this be done? For example a dropdown should probably not have this.

**Comment by ebruchez** [comment]
Next steps:

- [ ] group (in a nested way) by section
  - [ ] group
  - [ ] output nested `<ul>`'s in the email
- [ ] improve checkboxes
- [ ] repeats

**Comment by ebruchez** [comment]
Split out function to return all control values to #3627

**Comment by ebruchez** [comment]
[Documented `xxf:process-template()
 `](https://doc.orbeon.com/xforms/xpath/extension-functions/core-functions#xxf-process-template)
