### ISSUE TITLE
Test FastClick doesn't introduce regressions

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2476]

**Comment by ebruchez** [comment]
First step is testing forms with an actual iPhone and addressing issues if any.

**Comment by ebruchez** [comment]
Issue to keep in mind:

- selection issue (on iPhone 6S Plus) when clicking button?

**Comment by ebruchez** [comment]
Tried out our demo forms. There is an interesting behavior when you just press a button, hold, then drag. That will select some text on the page, and when you release the press, the button action will run, and if some text is selected the iOS copy/paste menu will come up too. This should probably not happen.

Not considering this a showstopper for now, especially since an upcoming version of Safari will likely fix that ([fixed in WebKit already](https://bugs.webkit.org/show_bug.cgi?id=149968)). So closing for now.

**Comment by avernet** [comment]
It's already supposed to be in 9.3, and ideally this behavior wouldn't kick in with 9.3. FastClick has an issue for this (https://github.com/ftlabs/fastclick/issues/450), but unfortunately the project doesn't seem to be very actively [maintained](https://github.com/ftlabs/fastclick/commits/master).

**Comment by ebruchez** [comment]
Cool. Entered #2709 to track that.
