### ISSUE TITLE
Date picker not accepting changes

### ISSUE THREAD

**Issue by ewg118** [orbeon/orbeon-forms#2543]
In the version of Orbeon I cloned several days ago, I noticed that the date picker widget is broken. The calendar pops up, but clicking on a day doesn't change the value of the input.

**Comment by avernet** [comment]
I am not seeing this problem here:

![screencast](https://cloud.githubusercontent.com/assets/106961/13015402/b4ce1c76-d16d-11e5-9160-e5dbbdb94d93.gif)

Can you try with a build created by our build system: [orbeon-4.10.0.pre.201602112326-CE.war](https://drive.google.com/open?id=0B_IAL5I44D2PMF9LVEp2al9ySG8).

**Comment by ewg118** [comment]
Hrm, oddly enough it is still not working. I have tested the current versions of Chrome and Firefox, so I don't know how to pinpoint the problem.

**Comment by avernet** [comment]
And you tried this with the build linked above, without any change to any of the config files, using a form with just one date field created in Form Builder?

**Comment by ewg118** [comment]
No, I didn't create the form in Form Builder. I made an .xhtml file from
scratch. Is that a problem?

**Comment by avernet** [comment]
Not at all: I'm just trying to get to a case that I can reproduce. Could you create an as-simple-as-possible version of such a file that shows the problem with the war linked earlier, and share that file with me, so I can investigate the problem? (I have no doubt there is a problem, but can't do much if I can't see it!)

**Comment by ewg118** [comment]
Okay, I have definitely identified some sort of problem, but I am not quite sure how to describe it. Here is a gist for a form with a working example and a non-working example: [https://gist.github.com/ewg118/32e6c2b7c4e15cdfbcdf](https://gist.github.com/ewg118/32e6c2b7c4e15cdfbcdf)

If the date element is presently in the model on form load, then the date picker will function correctly. If another model is loaded via XForms submission, the date picker doesn't change the element value. I commented out the xforms-submit-done actions on the get-records submission and the xforms-value-changed actions on the publication_date element, and this hasn't impacted date picker functionality.

I am not quite sure what version of Orbeon I was running on my development machine before building a new WAR out of the repo. Probably ~4.6.

**Comment by avernet** [comment]
In `Calendar.coffee`, in `setValue()`, it is somewhat strange that we set the `value` attribute, as the value won't have any effect if `.value` has been set. I'm not sure why we were doing it this way as opposed to using jQuery `.val()`.

The issue is fixed, and I'll follow-up here with a link to a test build for testing, once produced by the build system.

**Comment by avernet** [comment]
And [here is a CI build](https://drive.google.com/open?id=0B_IAL5I44D2PVUNOXzZSc3RkMjA) that includes those changes. @ewg118, if you get a chance to test it, you'll let us know how if this indeed resolves the problem for you.

**Comment by ewg118** [comment]
Great! I have confirmed that this build does fix the problem I was experiencing.

**Comment by avernet** [comment]
Very good, thank you for checking, and letting us know about the issue.
