### ISSUE TITLE
Alert shows for required Radio Buttons with "Other" when form is loaded

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2562]
Instead, we should only show the alert after the field has been visited, as we do for other fields.

![screen shot 2016-02-22 at 11 44 21 am](https://cloud.githubusercontent.com/assets/106961/13230294/a5b25e02-d959-11e5-803a-0c4aefd4b585.png)

**Comment by ebruchez** [comment]
I see a related issue which is that the control gets focus immediately upon form load.

**Comment by ebruchez** [comment]
This is because when the user clicks on "Other", we want to automatically focus on the input field. But at the time the radio button is activated, the input field is not visible yet, so `setfocus` within the handler doesn't work. That's why we used `xforms-enabled`. But that's called also upon initial display of the control.

Ideally, we could do like in JavaScript: dispatch an event to the event queue. In fact we can, using `<dispatch delay="1">`. Could that work?

**Comment by ebruchez** [comment]
Entered #2564 to address delayed event issues.

**Comment by avernet** [comment]
I'm most likely not getting the whole story, but wouldn't setting the focus on `xforms-select` when "other" is selected, instead of reacting to `xforms-enabled` do the right thing in this case?

**Comment by ebruchez** [comment]
@avernet Well no, as explained above: the input field is then non-relevant, and so focusing on it doesn't do anything.

In order to change that, I tried also setting the value of the radio buttons to blank, doing an `xf:refresh`, and then an `xf:setfocus`. But then, if the radio buttons didn't have focus already, `xf:setfocus` sets focus to the input field, which then reverts to the radio buttons when the default action of the `xforms-select` event runs! Code:

```xml
<xf:action event="xforms-select" if="xxf:is-blank(event('xxf:item-value'))">
    <xf:setvalue ref="."/>
    <xf:refresh xxbl:scope="outer"/>
    <xf:setfocus control="input"/>
</xf:action>
```

Hence trying `xf:dispatch` with a zero delay, which is failing for 3 or 4 different reasons!
