### ISSUE TITLE
Date and Time field not to show error after date is selected

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2570]
Currently, if you select a date with the date picker, the control shows an error as soon as the selection is made. Instead it should behave as it does now when the user types a date and tabs to the time field: only show an error if the date+time are invalid once the user tabs out of the time field. Concretely, once the date is selected, we should set the focus on the time field, and not show an error.

![screen shot 2016-02-24 at 11 12 24 am](https://cloud.githubusercontent.com/assets/106961/13297568/d1fa8f4a-dae7-11e5-9457-1ccc23a52ada.png)

[+1 from community](http://discuss.orbeon.com/input-field-type-xf-dateTime-validation-error-after-date-selection-td4661115.html)

**Comment by orbeon** [comment]
When a date is selected in the date picker:

1. The `<a>` corresponding to that day in the date picker gets the focus.
2. YUI's JavaScript, reacting to an event, removes the focus from the `<a>`.
3. YUI calls our code, which reacts to a date being selected.
4. YUI closes the date picker.

It is unclear to me why YUI does a blur on step 2, as the `<a>` would loose
the focus anyway when the date picker is closed. Maybe they had in mind
cases where the date picker is always visible (just shown inline in the
page), and leaving the focus on the `<a>` wouldn't look good? Anyhow, I
removed that from the YUI's code.

With this, we can, on step 3, set the focus back on the input field. This
way the control never looses the focus, no blur is sent to the server, and
thus the date-time field isn't marked as invalid when just a date is
selected.

As a bonus, since the date has the focus, users can hit tab and enter a
time.

**Comment by avernet** [comment]
When a date is selected in the date picker:

1. The `<a>` corresponding to that day in the date picker gets the focus.
2. YUI's JavaScript, reacting to an event, removes the focus from the `<a>`.
3. YUI calls our code, which reacts to a date being selected.
4. YUI closes the date picker.

It is unclear to me why YUI does a blur on step 2, as the `<a>` would loose the focus anyway when the date picker is closed. Maybe they had in mind cases where the date picker is always visible (just shown inline in the page), and leaving the focus on the `<a>` wouldn't look good? Anyhow, I removed that from the YUI's code.

With this, we can, on step 3, set the focus back on the input field. This way the control never looses the focus, no blur is sent to the server, and thus the date-time field isn't marked as invalid when just a date is selected.

As a bonus, since the date has the focus, users can hit tab and enter a time.
