### ISSUE TITLE
Handwritten signature: weird behavior when not initially shown

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2622]
- create form in [gist](https://gist.github.com/ebruchez/83403cb07c9ab3a14548)
- quickly click in 1st signature: things seem ok
- open 2nd section
- quickly click in 2nd signature: signature image appears to become smaller and smaller

**Comment by avernet** [comment]
The case where the canvas wasn't initially visible wasn't handled. With https://github.com/orbeon/orbeon-forms-pe/commit/a6dc1045ad3f4aa443b9f2f06dd9323d81ad8fe3, now it is. However, in this particular example, the component on the second page still fails to show properly, which I'll need to investigate.

**Comment by avernet** [comment]
It turns out https://github.com/orbeon/orbeon-forms-pe/commit/a6dc1045ad3f4aa443b9f2f06dd9323d81ad8fe3 did fix this.

The issue I was seeing was due me having locally set `oxf.fr.detail.view.appearance.*.*` to `wizard`, and when a section isn't *Initially Open*, with the wizard appearance its content just isn't shown, and there is no way for users to show it. So closing this, and created #2655 for ignoring *Initially Open* with the `wizard` appearance.
