### ISSUE TITLE
Dialogs don't center vertically anymore in Form Builder

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2674]

**Comment by avernet** [comment]
This is happening because, in `AjaxServer.js`, we used to show dialogs after making controls relevant. Now, we are doing it in the order specified in the Ajax response, and the server tells us to show the dialog first. When it happens in that order, if we show and center the dialog without its content being relevant, the centering isn't "correct" anymore after its content is made relevant. To solve this, we could:

- Change the code in `AjaxServer.js` to handle `<xxf:dialog>` after `<xxf:control>`, as it used to be the case.
- Change the server to send the `<xxf:dialog>` after the `<xxf:control>`.
- Change the code showing the dialog to delay centering to the end of the Ajax request.

I'm having a preference for this 3rd technique, as it keeps logically close code also close in the source ("show the dialog" and "do the centering after showing other controls").

In all cases, this is a heuristic, and the dialog might end up as not being centered if a control inside the dialog shows itself asynchronously.
