### ISSUE TITLE
Decide what to do with spinner button

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2676]
Now we have `fr:process-button` which uses `fr:ladda-button` (which implements support for a spinner within the button).

- the spinner button is enabled for `save-final` by properties
- there is still a test for the old `modal` button
    - but it is hardcoded in `fr:process-button` 
    - and doesn't work because the class is now on the container element

Changes, from @avernet:

- user should be able to choose between spinner button and modal spinner
- some other buttons, like Form Builder's Publish button, should have the spinner

**Comment by avernet** [comment]
Currently, this is what I am seeing:

- In Form Builder, neither the Ladda spinner , nor the regular spinner, nor the XForms loading indicator show on Save or Publish.
- In a published form, Ladda is used for Save.

For:

- The XForms loading indicator now showing, see #2683.
- The Ladda spinner are not showing in Form Builder because by default we only show the Ladda spinner for `save-final` and Form Builder uses `save`. So we'll be adding `save` and `publish` for `orbeon/builder`.
- For the regular spinner, `fr:process-button` puts the class `xforms-trigger-appearance-modal` on the `<fr:ladda-button>`, so it ends up in the HTML for the container of the Ladda button. The code in `xforms.js` tests on the class being on the trigger inside the Ladda button container.

Suggestion:

For this last point, we could, in `ladda-button.xbl` copy the class `xforms-trigger-appearance-modal` on the trigger, but I suggest that, to keep things simpler, we just use the Ladda button, which is more "modern", avoid flashing, and is what Gmail does when sending an email. Then, if customers mention this is a problem, we can bring back the modal spinner, and make it configurable.

**Comment by avernet** [comment]
The new behavior is documented in the [Loading indicator for buttons](http://doc.orbeon.com/configuration/properties/form-runner.html#loading-indicator-for-buttons) section.
