### ISSUE TITLE
Itemset Editor: automatic value remains invalid

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2715]
- add Radio Buttons
- add item
- enter label
- tab to value, notice value is automatically generated
- tab to hint
- value remains invalid
- Apply doesn't work

![screen shot 2016-04-13 at 4 36 32 pm](https://cloud.githubusercontent.com/assets/105769/14512689/198888f6-0196-11e6-9b60-a4ffd408bcba.png)

**Comment by avernet** [comment]
In executeNextRequest, we have 3 events in the queue: a value change for the label, for the value, and focus on the value, which is correct, but in the body of that function the value change for the value input gets filtered out, which we don't want.

This is happening because we listen to the `change` event on the label input, which happens before the `focus` event on the value input. On `change`, we set the value, which creates an event. On `focus` we set the server value to the current value. Then, when before sending the Ajax request, we filter the event, as we believe the server already knows about the value.
