### ISSUE TITLE
Wizard: subsection navigation

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2754]
Requirements:

- configured by property
- two levels: top-level sections, one level of subsections
- show one subsection at a time instead of all subsections
- "Next" goes to next subsection, and then next section
- some sections might not have any subsections
- grids at level of subsections can be ignored for now

[+1 from customer](https://mail.google.com/mail/u/0/#search/2693/153ee151ed538822)

**Comment by theelectricwiz** [comment]
+1

(from #2761)

Hey guys,

It would be awesome if we could display a sub section per page in wizard view. We are currently working on a form where we have had to split related questions into different pages using the wizard view. One sub-section per page would be very handy in that we could then group the related sub-sections into a single section (that we could then also move to a section template form).

Might be handy to be able to set this in a depth sort of parameter, so that if you were feeling.. adventurous, you could have sub-sub-sections appearing on separate pages. It could be a properties-local.xml property and/or an attribute that could be set up each fr:section element.

Cheers.

**Comment by ebruchez** [comment]
@theelectricwiz The good news is that this is now implemented and will be in 2016.2, but only one level of subsections are supported.

**Comment by ebruchez** [comment]
[Documented](http://doc.orbeon.com/form-runner/feature/wizard-view.html#subsections-navigation)

**Comment by theelectricwiz** [comment]
Groovy. Cheers.

**Comment by theelectricwiz** [comment]
Hey Eric,

Just wanted to confirm the working of 2016.2. Say if we have a form

```
section-1
  subsection-1-1
  subsection-1-2
section-2
  subsection-2-1
  subsection-2-2
```

and say section-1 has no grids in it, but section-2 does have grids and controls, will the wizard with subsection navigation navigate through it like:
`subsection-1-1, subsection-1-2, section-2, subsection-2-1, subsection-2-2` (ie skip section-1 as it is empty)

**Comment by ebruchez** [comment]
@theelectricwiz It will go through `subsection-1-1`, `subsection-1-2`, `subsection-2-1`, and `subsection-2-2`. It will not show either of `section-1` or `section-2` separately, whether they contain top-level grids or not. Top-level grids are simply excluded from navigation at this time.

**Comment by theelectricwiz** [comment]
Thanks Eric

**Comment by ebruchez** [comment]
We now have made changes so that nested grids are not ignored but work like sections, one grid at a time.
