### ISSUE TITLE
Migrate `xxf:dialog` to use `<dialog>` instead of YUI dialogs

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2835]
[+1 from customer](https://basecamp.com/1721271/projects/11908529/messages/58471721#comment_424052434)

**Comment by ebruchez** [comment]
Tasks:

- [ ] check usage of YUI dialogs in `xforms.js` and `AjaxServer.js`
- [ ] check what to do with `neighbor` parameter
- [ ] fix layout issues in Form Runner dialogs
- [ ] fix layout issues in Form Builder dialogs
- [ ] check whether we can remove some YUI files

See [Modals bootstrap-modal.js](http://getbootstrap.com/2.3.2/javascript.html#modals).

**Comment by avernet** [comment]
Before going with the Bootstrap dialog, we should consider using the [HTML 5.2 `<dialog>`](https://keithjgrant.com/posts/2018/meet-the-new-dialog-element/). Right now, it is [only supported by Chrome](https://caniuse.com/#feat=dialog), but will be soon supported by Firefox, and [this polyfill](https://github.com/GoogleChrome/dialog-polyfill) provides support for other browsers, including IE9+.

**Comment by ebruchez** [comment]
The native `<dialog>` + polyfill looks like a great solution. I suggest we go for it.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/4956383295), for the "close" in the toolbar to be accessible

**Comment by ebruchez** [comment]
- [ ] decide: HTML `<dialog>` or Bootstrap 5 dialog

**Comment by ebruchez** [comment]
RESOLUTION: Let's use Bootstrap modals.

**Comment by ebruchez** [comment]
Without using Bootstrap, made some progress with #5283:

- centering with CSS
- more modern look
- simplified/fixed initialization code

Issues:

- draggability is gone
- dialogs with neighbors don't position next to neighbor

It probably wouldn't take much to complete this. We may or may not use Bootstrap 5 styles.

**Comment by ebruchez** [comment]
YUI `container.js` handles things like preventing focus outside of containers/dialogs. Do we need some custom code to do that?

- [ ] make sure #5912 doesn't regress

**Comment by ebruchez** [comment]
- [ ] when migrating, also include a11y issues, including title on the close button #6271

**Comment by ebruchez** [comment]
RESOLUTION: use the [Bootstrap 2.x modal](https://getbootstrap.com/2.3.2/javascript.html#modals). Later, we'll upgrade to the latest Bootstrap.

**Comment by avernet** [comment]
We won't support:

- `appearance="minimal"`
- `level="modeless"`
- `draggable="true"`

We will only support the following attributes:

- `close="true | false"` (default: `true`)
- `visible="true | false"` (default: `false`)

**Comment by avernet** [comment]
Did the first rough step at switching to the HTML native `<dialog>`.

One problem is that when TinyMCE is displayed inside a dialog, as is the case in the Control Settings dialog when editing an HTML label, the toolbar for the editor in inline mode appears below the dialog, making it invisible.

TinyMCE creates the `<div>` for the toolbar directly inside the `<body>`. One idea would be to provide TinyMCE with a container in which to create the toolbar. TinyMCE's configuration has a `fixed_toolbar_container_target` for that purpose. When set, TinyMCE does create the toolbar `<div>` in the correct place, but the toolbar becomes "sticky" (TinyMCE terminology) instead of floating. I haven't found a way to both provide a container and have a non-sticky toolbar.

Some other ideas I can try next:

- Search further for others who have encountered this problem.
- Leave the toolbar inside the `<body>` and use a `z-index` to display it above the `<dialog>`.

**Comment by avernet** [comment]
- [ ] Check the source editor doesn't have a very large height for performance

**Comment by avernet** [comment]
- [ ] Make the dialog scrollable, see [my question on Stack Overflow](https://stackoverflow.com/q/78747714/5295) for scrolling issue I was encountering
