### ISSUE TITLE
Prune not working correctly when form contains repeated grid (Orbeon 4.10)

### ISSUE THREAD

**Issue by Norskov** [orbeon/orbeon-forms#2930]
I'm not quite using the newest version, so apologies if this has already been fixed.

I noticed this behaviour in one of our forms. It can be replicated by creating a new form with two sections and setting the visibility of one to false(), we'll call the visible section A and the invisible B . If you put a repeated grid in A, then B will be in the XML after pruning. If you don't have a repeated grid in A, then B will not be in the XML.

[Example of XML without repeated section](https://github.com/orbeon/orbeon-forms/files/474194/Without.txt)
[Example of XML with repeated section](https://github.com/orbeon/orbeon-forms/files/474193/With.txt)

**Comment by ebruchez** [comment]
I confirm the issue. It happens in `pruneFormRunnerMetadata()` where we make a copy of the data to a mutable document, thereby losing relevance data.

**Comment by ebruchez** [comment]
- [ ] figure out how to keep `instanceData` when migrating the data (or prune before)
- [ ] unit test
- [ ] backport fix as appropriate

**Comment by ebruchez** [comment]
Found two related issue when sending in `fr-send-submission`:

1. `migration:dataMaybeMigratedFrom()` happens when the data is migrated
2. `migration:pruneFormRunnerMetadata()` when the data is not migrated but just the metadata is pruned (this is also called by `migration:dataMaybeMigratedFrom()`

Cases where pruning works is:

- the data format is set to `edge` AND `prune-metadata` is set to `false`
- the data format is not set to `edge` AND there are no repeated grids in the form AND `prune-metadata` is set to `false`

In the other cases it fails.

**Comment by ebruchez** [comment]
Ideas to create unis tests for this and other `send` parameters:

- see `ItemsetActionTest` for an example of Form Runner test
- need to be able to run a process dynamically in the context of a test doc
  - add event handler running `fr:run-process()`
  - dispatch an event to the form with the process as parameter
- test result
  - use `replace="instance"` in process
  - this places the result in a well-known instance

**Comment by ebruchez** [comment]
Fix is now backported to 2016.2 and 2016.1. Checking if backport to 4.10 is needed.
