### ISSUE TITLE
Form description does not support HTML

### ISSUE THREAD

**Issue by acspike** [orbeon/orbeon-forms#2955]
The form description does not support HTML.

**Comment by ebruchez** [comment]
Wouldn't be too hard to do:

- we do something similar for control help where we have a "Use HTML" checkbox
- we would need to store the fact that the content is HTML in the `<description>` element

**Comment by avernet** [comment]
[+1 from user](http://discuss.orbeon.com/Form-description-td4665186.html)

**Comment by ebruchez** [comment]
The description is displayed:

- on the detail page
- in the Form Builder Summary page

When we display it, we need to do it differently if it's HTML. Not sure if it's an issue for the Form Builder Summary page.

**Comment by ebruchez** [comment]
- [x] implement in Form Builder
- [ ] support HTML in Form Builder Summary page

**Comment by ebruchez** [comment]
I implemented support in Form Builder by adding an attribute on the description. We can have:

```xml
<description xml:lang="en">My description</description>
```

Or:

```xml
<description xml:lang="en" mediatype="text/html">My description with &lt;some&gt; markup.</description>
```

The problem now is the Summary page. It has access to the form definition, but here the form definition is "Form Builder", of which of course there is only one.

Form Builder has hidden controls for helping the Summary page, including:

```xml
<xf:output id="description-control" bind="description-bind" class="fr-summary fr-search">
```

But we cannot discriminate forms that have an HTML description and those that don't, say, by checking `<xf:output mediatype="text/html">`, because either Form Builder has `mediatype="text/html"` or doesn't.

Can we switch Form Builder to always use `mediatype="text/html"`? This raises the question of backward compatibility with existing forms. For example an existing form might have a description with opening and closing pointy brackets, although that is not very likely.

Form Builder could migrate old descriptions by escaping them. But what should the Summary page do?

**Comment by ebruchez** [comment]
For now, implement heuristic on the Summary page, whereby, specifically for Form Builder, we display the value as HTML if its content starts with `<div>`.

**Comment by ebruchez** [comment]
So we have a workaround to detect the HTML. Another question is how to show the HTML in the grid. If we just show it as HTML, Summary page rows might become very tall (say when you add bullet points). I tried that. Maybe we need to de-style the HTML.

**Comment by ebruchez** [comment]
Alternatively, we can use CSS to inline elements.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-builder/form-settings#general-settings)

**Comment by ebruchez** [comment]
I notice an issue if the descript contains a link (`<a>`). Because the table cell already contains a link, the browser reorders the HTML elements (see [Nested Links](https://css-tricks.com/nested-links/)).
