### ISSUE TITLE
Ajax loading indicator not showing in Liferay

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3010]
[+1 from customer](https://basecamp.com/1721271/projects/5821856/messages/64353866)

**Comment by ebruchez** [comment]
Tentatively moving to 2017.1 as customer would like to see this fixed even though it is not a major issue.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1977373/messages/351671494)

**Comment by avernet** [comment]
The NProgress loading indicator isn't showing, as the CSS refers to an id, `#nprogress`, that id is used as-is in the DOM, but when the CSS is served by Orbeon Forms, that id is prefixed: `#o0nprogress`.

NProgress doesn't have an API to choose another id. Also, there is no class in the generated element that we can refer to in the CSS (instead of the id). So we can either:

1. Change the NProgress JavaScript to allow for the id to configured. That id is used in a few places, and changing the NProgress JavaScript would make upgrading NProgress harder.
2. Change the NProgress CSS so it isn't rewritten by Orbeon Forms. This is a simpler than point 1, but still requires a change to the NProgress source when upgrading.
3. Change the Orbeon Forms rewrite so it is able to handle exceptions (at least for ids), and list `nprogress` as an exception.
[](url)
Doing 2, specifically, replacing `nprogress` by `[id = "nprogress"]` is trivial, and seems safe. So going for this for now. But this really looks like a workaround, that can cause more work to maintain down the road, so we'll discuss implementing point 3, or some other solution.
