### ISSUE TITLE
xf:submission to support newline characters in JSON

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3012]
[A service](https://api.myjson.com/bins/2eq0h) returns the following JSON:

```json
{
  "firstName": "John",
  "lastName": "Smith",
  "address": "1000 Main Street\nNew York, NY"
}
```

We call it form a service defined in Form Builder, and with an action set the value of a text area to `/json/address`. The text area should show "1000 Main Street" and "New York, NY" on 2 separate lines. However, right now, they are shown on the same line with an unexpected character between the two.

This can be reproduced with [this form](https://github.com/orbeon/orbeon-forms/files/618191/scratch_2.txt).

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/302762014)

Next:

- [ ] Check if this indeed an issue, and not a problem with the example.
- [ ] See if there are other similar situations (see "char" in the [spec](http://json.org/)) that we're currently not handling properly.

**Comment by ebruchez** [comment]
[RFC 7159](https://tools.ietf.org/html/rfc7159) allows (and requires) escapes using `\`:

> All Unicode characters may be placed within the quotation marks, except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).

We first need to check that the JSON parser we use handles those escapes correctly (it probably does).

However, the [XForms 2.0 spec](https://www.w3.org/community/xformsusers/wiki/XForms_2.0#External_JSON_values) says that:

> (\b, \f, and characters of the form \uxxxx less than \u0020) are transformed by adding \uE000 to them.

So that's what we implement, but it's not very reasonable in the case of `\n`. In fact, XML supports the following characters below `0x20`:

    #x9 | #xA | #xD

I suggest the following:

- we change that in our implementation
- we recommend to the XForms 2.0 Community Group to amend the spec to reflect that

**Comment by ebruchez** [comment]
[Message to public-xformsusers@w3.org ](https://lists.w3.org/Archives/Public/public-xformsusers/2016Nov/0112.html)

**Comment by avernet** [comment]
And do already handle `\"`, `\\`, and `\/` as expected, i.e. not adding ` \uE000`?

**Comment by ebruchez** [comment]
`\` escapes should be handle by the JSON parser.

**Comment by ebruchez** [comment]
Confirm in XForms call that intent was to support `#x9 | #xA | #xD`.
