### ISSUE TITLE
Control Settings dialog fails to load if control itemset is hierarchical

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3148]
Even though we don't yet support hierarchical itemsets, the Control Settings dialog should still open.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2009991/messages/304584994#__recording_423556525)

See also #3125.

**Comment by avernet** [comment]
The issue happens when `fbf:readDefaultAlertAsXML($form, $i/control-name)` runs. For that control, in `AlertDetails.fromForm()`, `alertsByLang` is empty, because the source of the form is missing the "resource holder" for that control; that is: there is no `<matterControl>` inside any of the `<resource xml:lang="…">`.

Since we call `AlertDetails` only if `canHandle`, for which we already have conditions, and since `AlertDetails` requires that its `messages` parameter is non-empty, it seems natural to add `alertsByLang.nonEmpty` as a condition to `canHandle`.

At least, with this, form authors will be able to open the dialog, but other things things won't work if Form Builder can't find the resource holder. For instance, form authors will be able to set the control label; or rather, they will, but if they save and reload the form, the label won't be there. Adding missing resource holder could fall under #1491.
