### ISSUE TITLE
When switching to another wizard page with a setfocus, the page number isn't updated

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3309]
To reproduce, paste [this form](https://github.com/orbeon/orbeon-forms/files/1157662/scratch_80.txt) in Form Builder, publish, open `/new`, click save, click on the error in the error summary. Notice how we're now on the second page, but the screen still reads "1 of 2". Also, the same thing happens when clicking on the "Set focus" button on the first page of the wizard.

![screen shot 2017-07-18 at 5 47 28 pm](https://user-images.githubusercontent.com/106961/28345807-617356e4-6be1-11e7-9d52-bcb024a8fc61.png)

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966717/messages/597053845)

**Comment by ebruchez** [comment]
In this example, we dispatch `xforms-focus` to a control. The control is in the 2nd page of the wizard, so in the 2nd `case` of the `switch` which is introduced by the wizard. If the control is found and the focus can happen per XForms, then the `switch` toggles the `case` and so shows the wizard page.

But besides that, there is nothing that the wizard knows about when this change of case happens.

What we should do:

- upon capture of `xforms-focus`, check that the toggle to the specific page is allowed
- if not allowed, cancel the event
- if allowed, first switch to the page first so that all the wizard's information is properly updated
  - this might focus first to the first focusable control of the page, so check that behavior

**Comment by ebruchez** [comment]
So how do we know whether toggling is allowed?

Currently, we have some `$allow-next` variable with logic which controls the "Next" button and `wizard-next`.

We also have some logic controlling TOC navigation. This uses `$top-level-section-disabled` to disable sections which cannot be clicked (I think).

Ideally, we would have a function like `fr:wizard-can-toggle-to($something)`, or `fr:wizard-toggle-page(fr:wizard-current-page($control))`.

**Comment by ebruchez** [comment]
Keeping in mind of the difficulty of determining what a "step number" is, see #2784.

**Comment by ebruchez** [comment]
So maybe something like `fr:wizard-toggle-page(fr:wizard-page-id($control))`. Statically, we produce ids on `xf:case`s based on `$static-section-id` (top-level) or `$section-or-grid-id` (nested). All those are distinct. Maybe we could use the section/grid name for toggling.

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/15d0ed09e20aee59) when using the client-side API

**Comment by ebruchez** [comment]
When we are in `free` mode, the logic is very simple. Of course the `lax` / `strict` modes are the difficult ones.

**Comment by ebruchez** [comment]
When `xforms-focus` comes from the client, we first check that the control is not hidden with `Focus.isHidden(control)`. So for the client API, we need another solution. Maybe a separate API/event.

So we have 2 issues:

- wizard page change when clicking on the Error Summary
  - uses `xf:setfocus` action which tries to toggle the `case`
- client API
  - filtered out if the target is in a hidden `case`

**Comment by ebruchez** [comment]
Separating client-side issue to #3322.
