### ISSUE TITLE
FB: Improve expand/shrink UI

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3345]
Now that #2738 is mostly done, we should create a better UI for:

- expanding grid cells in all directions (including up and left)
- resizing adjacent grid cells, especially those on the same row

The user should be able to drag cell borders and the grid should update as the user goes.

**Comment by avernet** [comment]
Client-side code handling the moving of "walls" needs the following API:

1. `canDragWall(cell: html.Element, wall: top | right | bottom | left): Boolean`
2. `possibleDragTargets(cell: html.Element, wall: top | right | bottom | left): List[Int]` (the result being a list of positions, from 0 to 12)
3. `previewDrop(cell: html.Element, wall: top | right | bottom | left, position: Int): Unit`

**Comment by avernet** [comment]
[Wall move operations](https://balsamiq.cloud/s79oi/po9jb/rCF98)

![issue 3345 - wall move operations](https://user-images.githubusercontent.com/106961/35165253-7828da82-fd02-11e7-881f-971a0ec1da2a.png)

**Comment by avernet** [comment]
In fact this already works great with repeats. It turns out the issue I had (and of course spent quite a bit of time trying to debug!), was happening in Chrome's Dev channel. With the latest version from Chrome's Stable channel (right now,64), everything works like a charm!

For reference the issue was that reading [`grid-row-gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-gap) was returning the string `normal`.

**Comment by avernet** [comment]
- [ ] When the page is scrolled, the wall shows too low by amount the page is scrolled.

**Comment by avernet** [comment]
- [ ] With the blue halo shown (somehow?!), when moving a wall, it goes under the text fields, as shown below.

![form_builder](https://user-images.githubusercontent.com/106961/36886247-40ecc5b0-1da0-11e8-87f2-3732163c4246.png)

**Comment by avernet** [comment]
Using brighter colors for walls:

![wall-accent-colors](https://user-images.githubusercontent.com/106961/37504746-b00b0d82-289d-11e8-9663-5f142cdebf4d.gif)

**Comment by avernet** [comment]
When users can move the right wall of a cell and the left wall of the cell to its right, since moving one or the other is the same, we would like to show a wall in the middle, instead of a wall to the right and another one to the left.

After implementing code to figure *when* that is possible and when it's not, I'm getting to the conclusion that it's *always* possible to show the wall in the middle ;). That is, we never have a situation where the wall to the right of a cell has a different height than the wall to the left of the adjacent cell to the left. I'll need to think a bit more about it before I revert the code I just wrote.

**Comment by avernet** [comment]
Revert to the way I was showing wall to either the middle or the side, instead of always the middle, otherwise if always shown on the middle, the wall will hide while we're still on it when we move the pointer towards an adjacent cell for which the wall can't be moved. However I had to fix the way that algorithm: the wall is in the middle if the both cells have the same height (for left/right walls) or same width (for top/bottom walls).

**Comment by avernet** [comment]
Closing, as I've implemented the last batch of improvements to this feature last week, and am not aware of any remaining significant issues. This is not to say they don't exist, but we can open new issues for those as they come up.
