### ISSUE TITLE
XPath error when relinquishing lease with form using a wizard

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3566]
To reproduce, load the `/edit` page of a form using the wizard, logged in and with the lease enabled, and click on the "Relinquish lease" button. The `orbeon.log` will have the following error: `Undeclared variable in XPath expression: $relevant-top-level-section-ids`.

[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/1017523858)

**Comment by ebruchez** [comment]
The issue appears because, when the lease is relinquished, the entire `fr-form-group`, andf so the wizard, are made non-relevant. This dispatches `xforms-disabled` events. Then, inside the wizard, this handler runs:

```xml
<xf:action event="xforms-value-changed xxforms-constraints-changed xforms-disabled" xxf:phantom="true">
    <xf:dispatch name="fr-update-section-status" targetid="fr-wizard-outer-group"/>
</xf:action>
```

It runs ok, except that `fr-update-section-status` is in a contest where `xf:var`s are non-relevant and so considered missing. Fixing #134 would help here.
