### ISSUE TITLE
`NoSuchElementException` on second `fr-send-submission`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3568]
The [exception](https://github.com/orbeon/orbeon-forms/files/1939786/scratch_128.txt) happens in the 2017.1.1 [data migration code](https://github.com/orbeon/orbeon-forms-pe/blob/tag-release-2017.1-pe/form-runner/jvm/src/main/scala/org/orbeon/oxf/fr/DataMigration.scala#L298). Also see the log from which this exception is extracted in the thread linked below.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966559/messages/1024406123)

**Comment by ebruchez** [comment]
The migration code doesn't seem to have fundamentally changed since 2017.1.1.

**Comment by ebruchez** [comment]
The line causing the issue is:

```scala
frAttributes.foreach (delete(_, doDispatch = false))
```

And we have a comment saying "Attributes OTOH can be deleted in document order just fine", might not be true in fact: there is an underlying `Stream`, and it comes down to `AttributeEnumeration`, which iterates over our DOM's attributes. If attributes are removed, the iterator can fail.
