### ISSUE TITLE
Cell icons often require moving out of the grid and back in or they don't show

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3603]

**Comment by avernet** [comment]
To reproduce, move the pointer inside the wall to the right of a control. Move it past the middle of the wall, and return to the cell with the control, to the left of the wall. Notice that the editors are not showing.

In this case, in `ControlEditor.scala`, `becomesCurrent` is called, but because `masked` is `true`, `showEditors(cell)` isn't called. The mask is set when the pointer enters a `dndContainer`, and unset when it leaves the containers, with the exception of when we're dragging.

We get rid of `previousCellOpt`, and instead update `currentCellOpt` in `wasCurrent`/`becomesCurrent`, independently of the mask. Then, on `unmask`, if we have a `currentCellOpt`, we show the editors for that cell.

**Comment by avernet** [comment]
- [ ] With this last change, however, if move the pointer quickly from a cell with a control to an adjacent cell with no control, the control editors show for the empty, while they shouldn't.

**Comment by avernet** [comment]
`showEditors` is called twice for the same cell, and the second time when it tried to see if there is a control, it finds the `.fb-control-editor-left` in the cell, which it takes to be a control, and thus incorrectly shows the control editor icons.

Making `showEditors` aware that the cell might contain editors solves the problem.
