### ISSUE TITLE
`save-final` not replacing file URI with URI pointing to persistence

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3629]
With 2017.1.1 PE, using the `properties-local.xml` below, create a form, add an upload field, publish, open the new page, attach a file, hit Save. Note in the XForms inspector the element still points to a temporary file.

```xml
<properties xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:oxf="http://www.orbeon.com/oxf/processors">
    <property as="xs:string"  name="oxf.fr.detail.buttons.*.*">
        save-final submit
    </property>
    <property as="xs:string" name="oxf.fr.detail.process.submit.*.*">
    	save-final
    </property>
    <property as="xs:boolean" name="oxf.epilogue.xforms.inspector" value="true"/>
</properties>
```

[+1 from user](https://3.basecamp.com/3600924/buckets/7873395/messages/1130723506)

**Comment by ebruchez** [comment]
So that's because the data is either migrated or copied before being saved. So attachments paths are replaced, but they do not update the form instance. This might have regressed with #3110 for 2017.1. Interestingly, #3084 reverts the attachments paths in case of error, and that worked with 2016.3, but doesn't do anything with 2017.1.

The consequence is that if you save, then re-save, the attachments are rePUT to the database.

The fix is not exactly trivial.

The current sequence from `trySaveAttachmentsAndData` is:

- `dataMaybeMigratedToDatabaseFormat` adds the `data-format-version` attribute on root element and
  - migrates the data if needed
  - otherwise copies it
  - can also prune metadata is asked
- `putWithAttachments`
  - collects attachments
  - saves attachments
  - updates attachments paths (this is always in a *copy* of the data)
  - saves XML data
    - restore attachments paths in case of error (on the copy of the data)

**Comment by ebruchez** [comment]
What we should do then is collect attachments on the source data instead of the migrated data.

**Comment by ebruchez** [comment]
In fact:

- the attachments should be collected in both places
- the paths updated in both places
- but restored only on original data if needed
