### ISSUE TITLE
JavaScript error when loading form through embedding API

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3646]
To reproduce, deploy the `orbeon.war` and `orbeon-embedding.war` that come in the Orbeon Forms distribution, go to `http://localhost:8080/orbeon-embedding/`, and you will see the follow error in the console. This happens with any form, and the error doesn't happen if loading the form directly (i.e. not through the embedding API).

<img width="587" alt="JavaScript error" src="https://user-images.githubusercontent.com/106961/42186258-d571ba90-7e00-11e8-8604-a774e23296e9.png">

[+1 from customer](https://3.basecamp.com/3600924/buckets/7060934/messages/1151853986)

**Comment by avernet** [comment]
[+1 from user](https://3.basecamp.com/3600924/buckets/7873395/messages/1163412981)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/1167789521#__recording_1178914242)

**Comment by ebruchez** [comment]
This happens in `initializeJavaScriptControls`, where `formInitData` is not found.

Thinking that this only happens when inline resources are disabled. Curiously with:

```xml
<property as="xs:boolean" name="oxf.xforms.inline-resources" value="true"/>
```

inline resources remain disabled in embedding mode. Should check that.

**Comment by ebruchez** [comment]
The last issue is because I am using an older `orbeon-embedding` WAR which sends "portlet" instead of "embedded" as `Orbeon-Client` header. With the latest, disabling inline resources works as expected. However, the condition should be to enable inline resources no matter what if the property is set to `true`, and that condition should be fixed.
