### ISSUE TITLE
Edge and IE11: Controls form: drawing signature causes JavaScript error

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3715]
<img width="1365" alt="screen shot 2018-09-05 at 11 58 41 am" src="https://user-images.githubusercontent.com/105769/45114884-162f0a80-b103-11e8-9530-9921a33fe99a.png">

**Comment by ebruchez** [comment]
Tried with Edge 17.

**Comment by avernet** [comment]
While interacting with the signature component on Edge, I am seeing 500 errors to requests done to `xforms-server`:

<img width="702" alt="screen shot 2018-09-06 at 8 51 03 am" src="https://user-images.githubusercontent.com/106961/45169260-0de1d880-b1b2-11e8-997c-9704497b2092.png">

But I'm not seeing any request arriving to the local Tomcat. While normal HTTP requests come from Tomcat, per the `Server` response header:

<img width="851" alt="screen shot 2018-09-06 at 8 54 43 am" src="https://user-images.githubusercontent.com/106961/45169489-92ccf200-b1b2-11e8-89f8-0cec51f5174a.png">

…the 500 come from "Monocle", which I imagine to the proxy used by Sauce.

<img width="854" alt="screen shot 2018-09-06 at 8 56 07 am" src="https://user-images.githubusercontent.com/106961/45169569-c3ad2700-b1b2-11e8-8615-502669fab110.png">

Now, why would the proxy cause any problem in that specific case?

**Comment by avernet** [comment]
- I can't reproduce the issue with Chrome on Sauce, so the 500 isn't entirely due to the proxy.
- With Edge, I don't reproduce the JavaScript error mentioned by Erik, only the 500. (Which is annoying, as this would give me something to debug.)
- If I clear Franklin's signature before scribbling, no 500 or other error happens.

**Comment by avernet** [comment]
- With IE11, everything works fine (no 500, no JavaScript error).
- I re-tested this using a verbatim build (`2018.1-pe` build 2261).
- Procedure: load the page in Sauce, F12, on Edge position Dev Tools at the bottom, reload page (so Dev Tools are there since the beginning), click on the console, click on Signature, scribble in signature.

**Comment by avernet** [comment]
Also, I am not reproducing the issue with Edge on VirtualBox, so I am considering closing this.

**Comment by ebruchez** [comment]
We can't seem to reproduce this and the issue might be due to the Sauce proxy. Will reopen if it happens in other circumstances.

**Comment by avernet** [comment]
I've tried to investigate the JavaScript error. By disabling minimal and combined resources found exactly where it is happening, but am puzzled as to why that error could ever happen there. For now, as I asked a [question explaining the situation on Stack Overflow](https://stackoverflow.com/questions/52227657/what-can-cause-a-script5007-object-expected-with-edge-17-in-this-situation).

**Comment by avernet** [comment]
With regard to the `SCRIPT5007: Object expected` error, someone on Stack Overflow suggested to do the test explicitly on `window.document`. Just something to consider if we hit this one again.
