### ISSUE TITLE
Help resizes repeated grid in Bookshelf form

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3871]
<img width="557" alt="screen shot 2018-12-31 at 3 45 45 pm" src="https://user-images.githubusercontent.com/105769/50569139-32d6fa00-0d13-11e9-9315-c4f76297af67.png">

**Comment by avernet** [comment]
The `div.popover` is added inside a `tr`, after a `th`, which doesn't seem like a good place. This is because we don't recognize the help as being "standalone", that is outside of the control, and not referring to the control. The code in `xforms.js` expects those LHHA to have an id ending with `≡≡p` with the help, but this isn't the case here.

This must have regressed when we changed how we output the LHH in the table headers. Adding code to handle those standalone LHH "controls" solves the problem.

**Comment by ebruchez** [comment]
Reopening as the commit is breaking buttons (and possibly more).

**Comment by avernet** [comment]
Fixed issue with buttons, closing.
