### ISSUE TITLE
Login page hardcodes path to /orbeon context

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3876]
See:

https://github.com/orbeon/orbeon-forms/blob/c281bd8143c7ce03e7adc4df1eff9aae6d48077c/form-runner/js/src/main/scala/org/orbeon/fr/FormRunnerPrivateAPI.scala#L57

This prevents login from working on prod.orbeon.com.

**Comment by avernet** [comment]
For this we need to know what the context path is (aka path info), and this on the client.

We have a similar need in the TinyMCE code: in that case we produce a link in the markup (see below), then in JavaScript go find that link and extract the part we're interested in.

```xml
<xh:a
    f:url-type="resource"
    href="/xbl/orbeon/tinymce/js/tinymce1b713b2e6d7fd45753f4b8a6270b776e.js"
    class="tinymce-base-url xforms-hidden"/>
```

We could move this capability to the XForms level, and have the server send this info to the client, say in `orbeonInitData`, instead of generating a dummy link in the page.

**Comment by ebruchez** [comment]
@avernet The login page an XForms page? If so, we already have some paths in there and we could add one.

Also, since the login page is unlikely to be embedded, we could just produce the context path.

**Comment by ebruchez** [comment]
Or, since we pass the username/password in the action, we could also pass the submission path at that time.
