### ISSUE TITLE
License button is not fully clickable

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3879]
Only the text is.

<img width="986" alt="click on whole button" src="https://user-images.githubusercontent.com/105769/50861210-d7c58880-134c-11e9-9383-3115ccb73f8e.png">

**Comment by avernet** [comment]
The download button is done with an `<xf:output appearance="xxf:download">`. In this case, there is no JavaScript involved, and it just the `<a>` doing the work, so we need to make it as wide and high as possible. We add the `btn btn-success btn-large` classes in the form's source, so the CSS will go in that specific form.

Should be fixed by https://github.com/orbeon/cloud/commit/c9f620bd3e05c18ff3b787e9ae8cd840d44c5426.

**Comment by ebruchez** [comment]
I did a pull and it does fix the problem. Closing
