### ISSUE TITLE
Occasionally getting empty page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3893]
With the following exception showing in the console:

<img width="616" alt="screen shot 2019-01-15 at 3 35 12 pm" src="https://user-images.githubusercontent.com/106961/51219020-c3046a00-18e3-11e9-852c-912260672165.png">

**Comment by ebruchez** [comment]
This is most likely due to #3565 and external scripts. When this is enabled, which is the default, we load dynamic data structures as external scripts. This includes:

- `xformsPageLoadedServer`
- `opsXFormsProperties`
- `orbeonInitData`

In order, things happen like this:

- load `jquery-*.js`
- load more supporting JavaScript files
- load `xforms.js`
- load more XForms JavaScript files
- load eventually `orbeon-form-runner.js`
    - completes the initialization of the `ORBEON` objects
    - registers `$()` for initializing the XForms processor
- loads external static XForms functions and data structures
- loads external dynamic XForms functions and data structures

Now surprisingly enough, it looks like jQuery's `$()` [can fire before `defer`ed scripts](https://github.com/jquery/jquery/issues/3271)! Very surprising, as it was meant to be a better `DOMContentLoaded`, and MDN [says](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) that:

> Scripts with the `defer` attribute will prevent the DOMContentLoaded event from firing until the script has loaded and finished evaluating.

It doesn't look like this is going to be fixed in jQuery proper.

So in our case, jQuery might run our initialization before the external static/dynamic JavaScript files are loaded.

We could poll for the presence of `orbeonInitData`, as a solution.

**Comment by ebruchez** [comment]
Also check whether `orbeonInitData` was mandatory in 2018.2 and earlier.

**Comment by ebruchez** [comment]
In [2018.1](https://github.com/orbeon/orbeon-forms/blob/2018.1-ce/xforms/jvm/src/main/scala/org/orbeon/oxf/xforms/processor/ScriptBuilder.scala) and [2018.2](https://github.com/orbeon/orbeon-forms/blob/2018.2-ce/xforms/jvm/src/main/scala/org/orbeon/oxf/xforms/processor/ScriptBuilder.scala), `orbeonInitData` is always output since we set `val hasPath = true`. So we could rely on this.

In 2019.1, refactoring makes this unconditional.

**Comment by ebruchez** [comment]
Verified that:

- delaying the load of the dynamic JavaScript (for example  with `Thread.sleep()`) causes the problem
- waiting for `orbeonInitData` to be ready on the client addresses the problem

**Comment by ebruchez** [comment]
We now have a fix for master which is based on heavily refactored client-side initialization. Now we need a fix for 2018.2 and earlier.

**Comment by ebruchez** [comment]
Fix for 2018.2 is ready too.

**Comment by ebruchez** [comment]
And fix for 2018.1 is ready.
