### ISSUE TITLE
Date picker fails to appear when field is shown after the page loads

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3909]
To reproduce, run [calendarissue2.xml.txt](https://github.com/orbeon/orbeon-forms/files/2794007/calendarissue2.xml.txt).

[+1 from user](https://3.basecamp.com/3600924/buckets/7873395/messages/1553265664)

**Comment by ebruchez** [comment]
To clarify: the field shows, but the picker doesn't when you click on the calendar icon.

**Comment by ebruchez** [comment]
So this is tricky. The response has:

```xml
<xxf:control id="section-1-section≡grid-1-grid≡date-2-control" label="Date" hint="" relevant="true">
    <xxf:value/>
</xxf:control>
```

`relevant="true"` causes `ORBEON.xforms.Controls.setRelevant()` to run, which causes `ORBEON.xforms.XBL.instanceForControl(control)`, which causes `init()`. But this, again happens before the following markup is processed:

```xml
<xxf:control id="section-1-section≡grid-1-grid≡date-2-control≡xf-630" readonly="true" relevant="true"/>
<xxf:control class="input-append date fr-field-width-full" id="section-1-section≡grid-1-grid≡date-2-control≡xf-635"/>
<xxf:attribute for="section-1-section≡grid-1-grid≡date-2-control≡xf-638" name="placeholder">MM/DD/YYYY</xxf:attribute>
```

**Comment by ebruchez** [comment]
What we'd like to achieve in general is that changes to the markup for the control and nested content is processed *before* the JavaScript lifecycle methods run.

Note that we need `xxf:init` in full updates because the markup is just set in the page, not updated incrementally. With incremental updates, `xxf:init` was not needed ' because `relevant` changes would do the needful. Except, that is, that it happens too early.

If the Ajax response had a nested format, this might help. So instead of:

```xml
<xxf:control-values>
    <xxf:control id="xf-291" relevant="true"/>
    <xxf:control id="xf-292" relevant="true"/>
    <xxf:attribute for="xf-293" name="title">Unsaved changes</xxf:attribute>
    <xxf:control id="section-1-section≡grid-1-grid≡date-2-control" label="Date" hint="" relevant="true">
        <xxf:value/>
    </xxf:control>
    <xxf:control id="section-1-section≡grid-1-grid≡date-2-control≡xf-630" readonly="true" relevant="true"/>
    <xxf:control class="input-append date fr-field-width-full" id="section-1-section≡grid-1-grid≡date-2-control≡xf-635"/>
    <xxf:attribute for="section-1-section≡grid-1-grid≡date-2-control≡xf-638" name="placeholder">MM/DD/YYYY</xxf:attribute>
</xxf:control-values>
```

We'd have:

```xml
<xxf:control-values>
    <xxf:control id="xf-291" relevant="true"/>
    <xxf:control id="xf-292" relevant="true"/>
    <xxf:attribute for="xf-293" name="title">Unsaved changes</xxf:attribute>
    <xxf:control id="section-1-section≡grid-1-grid≡date-2-control" label="Date" hint="" relevant="true">
        <xxf:value/>
        <xxf:control id="section-1-section≡grid-1-grid≡date-2-control≡xf-630" readonly="true" relevant="true"/>
        <xxf:control class="input-append date fr-field-width-full" id="section-1-section≡grid-1-grid≡date-2-control≡xf-635"/>
        <xxf:attribute for="section-1-section≡grid-1-grid≡date-2-control≡xf-638" name="placeholder">MM/DD/YYYY</xxf:attribute>
    </xxf:control>
</xxf:control-values>
```

Having processed the entire content of a control with nested content, the JavaScript lifecycle methods can run:

- `setRelevant`
- `setReadonly`
- `setCurrentValue`

Nesting might be a change a little bit too big for 2018.2.1. If the server could tell us instead when to run those initializations, that would be better. So:

- If any of relevance, readonliness or value has changed, place an `xxf:init` element.
- On the client client, the `setRelevant`, etc. methods do not handle XBL components.
- Instead, `xxf:init` processing does what is needed directly.
