### ISSUE TITLE
Allow form author to select the number of column in the grid/layout to values other than 12

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4134]
Some form authors might prefer:

- larger values (16, 24…) so they can put more fields on a given line or distribute the columns with more flexibility;
- smaller values (2, 3, 4…), for instance in cases where all the fields in a form are on 2 columns of the same width.

TBD: This option could be per form, per grid, or both (with the setting per grid overriding the setting per form).

[+1 from user](https://mail.google.com/mail/u/0/#inbox/FMfcgxvzMBmqgTPfQZQHgrzTKxWWqTsw)

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/FMfcgxwGCkmWFXStwlDSvnwRZgsDtvjq) who needs probably 25 columns.

We see grids as a way to align form fields. It doesn't seem unreasonable to support more than 12 columns. We could go one of two ways:

- pick another fixed number, such as 24, 30 or 60 for the grid
- let the form author choose (which can cause issues when changing the number)

Possible next steps:

- [ ] evaluate the impact on the code

**Comment by ebruchez** [comment]
A quick experiment, changing a constant in Scala and another in LESS, shows that things work pretty well with 24 columns, including the PDF output.

We are leaning towards making this configurable, to some extent at least, in Form Builder. We could have a list of predefined width like 12, 24 or 30.

One thing to solve is switching between widths. 12 → 24 is easy, as is 12 → 60. But depending on the current state of the form, the switch might require adjustments.

For example if you have a form with 12 columns and want to move to 30 columns, since 30 is not divisible by 12, you would have a cell that is a little narrower. The user should be warned about that.

Another way to go would be to disallow switching from a given width to another one if the form doesn't have cell widths that would allow a perfect migration. The option to change the format, in Form Builder, would tell the user that some grids cannot be migrated, ideally providing information about which ones.

So the proposal would be to add an option in Form Builder's form settings:

- default would be 12 for now
- add 24 and maybe others
- allow switching only if grids are compatible

Steps:

- [ ] add Form Builder option
    - [ ] decide where to store it: `fr-form-metadata`?
    - [ ] UI
- [ ] code to check the compatibility of migrating from one width to another
- [ ] code to migrate from one width to another
- [ ] all the code that uses `StandardGridWidth` must use instead an explicit parameter
- [ ] update the CSS to support the various sizes as needed
- [ ] make sure loading existing forms still work

Fastest path for the customer requirement:

- [ ] determine supported sizes
- [ ] no form UI but support setting in `fr-form-metadata` (edited by hand)
- [ ] all the code that uses `StandardGridWidth` must use instead an explicit parameter
- [ ] update the CSS to support the various sizes as needed
- [ ] make sure loading existing forms still work

**Comment by ebruchez** [comment]
I thought we might even let the code handle arbitrary sizes, even if we don't expose them, but the CSS in Form Builder can be tricky for that.

**Comment by ebruchez** [comment]
Since we see grids as a way to align things, what if we made the jump to 60?

- [ ] check how things would look like: fixed vs. fluid
- [ ] consider whether having fewer columns for fixed/more for fluid would make sense
- [ ] consider operations to align and spread (see below)

Like drawing software, it would be handy to have alignment functions, including:

- align l/r/t/b
- distribute evenly on grid width or specified area
- center
- take entire width
- all selected on 1/2/3/n columns
- possibly more

**Comment by ebruchez** [comment]
60 would be crowded, unless we make some other changes:

<img width="984" alt="Screen Shot 2020-01-21 at 3 38 07 PM" src="https://user-images.githubusercontent.com/105769/72852754-66f5c380-3c64-11ea-870a-a9b86ab16997.png">

**Comment by ebruchez** [comment]
"Other changes" might be showing a ruler or grid to make it clear where the major subdivisions are (1/2, 1/4, etc.). Even so, 60 subdivisions might be too much for our standard fixed-width form.

This issue intersects with the feature of fixed-width/fluid that we have now. We might, in the future, also have other options, such as "wide fixed-width" (which would better fit a landscape page).

For a "wide fixed-width" form, 60 subdivisions might make sense. For the regular fixed-width form, much less so. Could the number of columns depend on the type of grid? For example, we could have a "wide" grid with 60 subdivisions (or 24), and a narrow grid with 12 subdivisions.

A setting by grid (or section) could make sense, see also #4359.

So what if we allowed this setting to be changed for a given grid? The default would remain 12.

```
<fr:grid columns="24" ...>
```

The user would go to the grid setting and set for example "24 columns". Migration, if needed, would only have to operate at the time the user changes the setting, and only for the given grid. We wouldn't need to migrate existing forms/grids, which would be a plus.

Benefits of the per-grid option:

- no form-wide migration required
- easier migration when needed as it's less likely to have issues with one grid than with an entire form
- if many columns are "weird", they are probably so only for a small number of grids in a form

**Comment by avernet** [comment]
The above screenshot with 60 "stops" makes me think that even if the lines were made thinner, and the page was wider, it would be hard for users to align columns, and we might need to add several other ways to help users do that to make it usable.

So I like the per-grid option. A further improvement would be for form authors to be able to specify the percentage of each column. (This follows the direction that [Unsemantic](https://unsemantic.com), the successor of the [960 Grid System](https://960.gs), took.)

**Comment by ebruchez** [comment]
I am not sure about the percentage. Either the user snaps controls to fixed grid lines, or the columns themselves change size, but we can't have both at the same time.

**Comment by ebruchez** [comment]
RESOLVED: For the short-term, we implement a new option in Form Builder which enables support for 24 columns for a given grid.

- Form Builder option in Container Settings
    - [ ] option
    - [ ] migration 12 → 24
- `fr:grid` support
    - [ ] add outer class
    - [ ] CSS

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-builder/form-editor/grid-settings)
