### ISSUE TITLE
Fancy select1 appears under dialog

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4184]
It worked the first time, but later this happened.

<img width="1039" alt="Screen Shot 2019-09-18 at 11 43 57 AM" src="https://user-images.githubusercontent.com/105769/65176514-c2d7e380-da09-11e9-97f4-a8210adab3a9.png">

**Comment by avernet** [comment]
For the dropdown, Select2 creates a `span.select2-container` with absolute positioning. It contains a `span.select2-dropdown` with a `z-index: 1051`, while the `div.yui-dialog` has a `z-index: 1051`. If we close and reopen the dialog, the dialog gets a `z-index: 1052`, while the `span.select2-dropdown` still has a `z-index: 1051`, hence shows below the dialog.

Every time the client-side code shows a dialog, it increments `ORBEON.xforms.Globals.lastDialogZIndex`. We don't tell Select2 what `z-index` to use (e.g. in `Select1Search.scala`); instead, the `z-index: 1051` is hardcoded in `select2.css`. Since we always want the dropdown to show above everything else, we can override Select2's CSS, in our own `dropdown-select1-search.less` (which is included by both `dropdown-select1-search.xbl` and  `databound-select1-search.xbl`), to have a higher `z-index`, as [suggested on Stack Overflow](https://stackoverflow.com/a/51146463/5295).
