### ISSUE TITLE
Order of `<xf:action type="javascript">` and `<xf:load>` not respected

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4195]
Say you click on this button:

```xml
<xf:trigger>
    <xf:label>Script and load</xf:label>
    <xf:action event="DOMActivate">
        <xf:action type="javascript">console.log("Action");</xf:action>
        <xf:load resource="javascript:console.log('Load')"/>
    </xf:action>
</xf:trigger>
```

On the console, you'll get "Load" then "Action", while the reverse would be expected. ("Load" then "Action" also corresponds to the order of the events in the Ajax response.)

**Comment by ebruchez** [comment]
For #3718, we had a similar issue related to `xxf:submission`, which we changed to be the last to run.

Here, we should do something similar, and have `xxf:load` run last, but only if it's not a `javascript:` load. If it is a JavaScript load, it should run interleaved with the other scripts.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1956846/messages/1824859930)
[+1 from customer](https://3.basecamp.com/3600924/buckets/7449965/chats/1039071234)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966555/messages/2071042840#__recording_2095642392)

**Comment by ebruchez** [comment]
My first idea was to handle `<xf:load resource="javascript:...">` the same way we handle `<xf:action type="javascript">`. In particular, add it to the list of static scripts so that all scripts are handled the same way.

The problem is that we can use AVTs in `resource`. We have one (obsolete) instance of this in our code, and we actually document this as well. But scripts don't have AVTs. They can only have parameters. So we cannot handle them exactly the same way.

So, for now, we have to keep handling JavaScript loads separately. But what we'll do is:

- keep JavaScript loads invocations where they are now
- move all other loads to the end
