### ISSUE TITLE
Autocomplete Control - list is reinitialized (?) while using arrow keys to navigate

### ISSUE THREAD

**Issue by mkaminski93** [orbeon/orbeon-forms#4486]
Orbeon Forms version: 2019.2.0 CE

To reproduce bug:
_First variant:_
* Expand the list
* Press down arrow key (list should disappear after a while)
![6dce362803d2](https://user-images.githubusercontent.com/42934385/78116843-299c7780-7405-11ea-8b52-6c12d754091d.gif)

_Second variant:_
* Type something in text field
* Press down arrow key (selection will jump to first option after a while)
![99ca160931a7](https://user-images.githubusercontent.com/42934385/78116858-315c1c00-7405-11ea-9ca0-f1e645127068.gif)

**Comment by avernet** [comment]
@mkaminski93 At this point, since the autocomplete is deprecated, and will be automatically migrated to a Dynamic Dropdown with search (#4242), we are unlikely to fix issues happening with that control. So I am tentatively closing this as "won't fix", and recommend you change your form to use a [Dynamic Dropdown with search](https://doc.orbeon.com/form-runner/component/static-dynamic-dropdown).
