### ISSUE TITLE
Deadlock with SQL Server

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4515]
[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/2610178933)

**Comment by avernet** [comment]
Places where deadlocks happen:

- `CreateUpdateDelete.scala`
    - Line 225: deleting drafts from `orbeon_i_control_text`
    - Line 255: counting the number of drafts to delete, to only run the `DELETE` if there are any
    - Line 262: deleting drafts, most likely from `orbeon_i_current`, since this is the table mentioned in the graph
- `Reindex.scala`
    - Line 117: deleting either from `orbeon_i_control_text` or `orbeon_i_current`
    - Line 152: `SELECT count(*) FROM orbeon_form_data` to count the number of document we'll be reindexing
- `SearchLogic.scala`
    - Line 104: running a search, getting the total possible number of rows, running a `SELECT FROM orbeon_i_current`

**Comment by avernet** [comment]
Closing, fixed by new indexes.

**Comment by ebruchez** [comment]
Interestingly, there is another reference (which doesn't show above?) to this issue in `CreateUpdateDelete`, where a database `commit()` was added. See:

https://github.com/orbeon/orbeon-forms/blob/e791f8fb100de729aea89658e0d34c5dfa813a4d/form-runner/jvm/src/main/scala/org/orbeon/oxf/fr/persistence/relational/rest/CreateUpdateDelete.scala#L305-L314

The commit comment says:

> For #4515: commit after deleting drafts to avoid deadlock with reindexing

Curious, as the comment above seems to indicate that this is "fixed by new indexes". However, I see in separate conversations that the fix introduced with just the `commit()` is commented as "the fix did not work". But it might have been due to "freezes", which are a different issue.

Still, my question is whether the `commit()` in question is truly needed, in light of the indexes modification, also considering that now that we run the `reindex()` within the same transaction, and not a separate transaction.

**Comment by avernet** [comment]
The `connection.commit() ` was removed while working on #7164.
