### ISSUE TITLE
XForms support for multiple labels

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4758]
Currently, we support external labels, as in:

```xml
<xf:label for="my-input">Address</xf:label>
<xf:input ref="name" id="my-input"/>
```

But we don't support having several such external labels. For instance we don't have a way to tie the labels "Billing" and the label "Address" to the input field in:

```xml
<xf:label>Billing</xf:label>
<xf:label>Address</xf:label>
<xf:input ref="name" id="my-input"/>
```

We could do this either by supporting multiple labels points to a single field, or by supporting a way for fields to point to their labels. The latter technique seems preferable as it allows the form author to specify an order for the labels. Also, it is in line with what is being done in HTML. If we name the attribute `labeled-by`, the above example with the input field pointing to the two labels would look like:

```xml
<xf:label id="billing-label">Billing</xf:label>
<xf:label id="address-label">Address</xf:label>
<xf:input ref="name" labeled-by="billing-label address-label"/>
```

**Comment by ebruchez** [comment]
Changing the title to reflect the fact that we might want to support a combination of (probably a single) internal and external labels for #4491.

**Comment by ebruchez** [comment]
Right now, attaching more than one label, for example one external and one internal, works partially:

- the external label shows, and shows its value
- the internal label shows, and shows its value
- however, statically, only the second label is attached to the form control, because we use a `Map[LHHA, LHHAAnalysis]`

This means that there is no `labelledby` generated on the `<input>` field. However, is this a problem, since we do have the internal label anyway?

**Comment by ebruchez** [comment]
- [x] test
