### ISSUE TITLE
XPath function returning whether a form is embedded

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4976]
One use case would be to only show certain buttons when form isn't embedded, as the capability provided by those buttons isn't available when the form is embedded (e.g. PDF).

See `isEmbedded`.

[+1 from user](https://groups.google.com/g/orbeon/c/2vnl4dNp-Qk/m/XFCpSNVlAwAJ)

**Comment by ebruchez** [comment]
We have (`offline` branch) `def XFormsContainingDocumentBuilder.isEmbeddedFromHeaders` whose result  is passed to  `XFormsContainingDocument` and then that's used by `isEmbedded`. This uses the `Orbeon-Client` header with values `embedded` or `portlet`.

We also have some duplication in `def ServletExternalContext. isEmbedded` which also uses the headers. This is used to pick the URL `Rewriter` implementation as well as for `sendRedirect()`.

But we also have `def FormRunnerBaseOps.isEmbeddable` which uses the `orbeon-embeddable` request parameter. This is only used to pass `orbeon-embeddable` in actions when navigating/changing mode. So that's not what we are supposed to use.

`orbeon-embeddable` is used for theme selection in `epilogue-servlet.xpl` and to prevent showing the user menu in `view.xsl` (this should probably not use that, actually).

So embedding callers pass `orbeon-embeddable` to trigger the theme but we expect the embedding API to pass the header indicating the type of embedded client.

- [ ] clean-up
    - [ ] remove (most) uses of literal `orbeon-embeddable`
    - [ ] remove duplication of reading headers
- [ ] implement function
    - [ ] online: use `isEmbeddable`
    - [ ] offline: always `true`

**Comment by ebruchez** [comment]
BTW @avernet the PDF should work when the form is embedded.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/xforms/xpath/extension-functions/extension-form-runner#fr-is-embedded)
