### ISSUE TITLE
Support grids where cells are ordered by column (and not by row)

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5194]
Marking a grid as ordered by column will impact:

- The tab order
- The order in which the cell are placed on devices with a narrow display (phones) when all cells are stacked up

For the example below, both the tab order and order of the cell a responsive relayout will be:

- Ordered by row (current situation): A, B, C, D, E, F.
- Ordered by column (new option): A, D, B, E, C, F.

Example:

    Cell A    Cell B    Cell C
    Cell D    Cell E    Cell F

[+1 from customer](https://3.basecamp.com/3600924/buckets/4224335/messages/4570673989)

**Comment by avernet** [comment]
Code involved:

- `grid.xbl`
- `dialog-container-settings.xbl`

**Comment by ebruchez** [comment]
Actually `grid.xbl` is legacy. The new ones are `grid-single.xbl` and `grid-multiple.xbl`. They also use `grid-common.xsl`.

The source of the grid is processed in Scala via:

- `cell:analyze12ColumnGridAndFillHoles()`
- `cell:analyzeTrTdGridAndFillHoles()`

In the XSLT, in `fr:rows-content()`, I think we need to reorder the `<div>`s output. Not sure if we can do it in the above functions. They return essentially `List[List[_]]` where the outer list is "rows" and the inner one "columns". That probably shouldn't be changed.

But in `fr:rows-content()` we have access to all the `x`, `y`, `w`, and `h` of each cell.

Also: to do only if `$use-css-grids-output = true()`. The old tables output is only useful for the PDF and backward compatibility.

**Comment by ebruchez** [comment]
Additional thought: the only reason, in `grid-common.xsl`, that we need to iterate over rows and then cells, is to handle the case of `<xsl:when test="not($use-css-grids-output)">`, because this needs to output `<div>` or `<tr>` for rows. We don't handle this case for the tab order.

But in the other case, where we use CSS grids, we don't output anything that represent rows. We just output a `<div>` for every cell. So in this case when we compute `$cells-content`, we could have just a single "row" or "column", etc. It doesn't matter, in fact, whether we keep any notion of row. We just need to sort the cells "correctly".

**Comment by avernet** [comment]
Is what follows correctly restating or implied by what you're saying?

- In the case where we output just a `<div>` for each cell:
    - We could bypass the `analyze…` Scala code.
    - And instead "just" sort the cells before we output a `div.fr-grid-td` for each cell:
        - If `tab-order="row"`: first sort cells by `y` then by `x`
        - If `tab-order="column"`: first sort cells by `x` then by `y`

**Comment by ebruchez** [comment]
I don't think we can bypass because the source form could be a form with legacy `<tr>`/`<td>` cells. Also the `analyze` functions do some adjustments. Not sure if we can bypass them. In any case it's safer to just still call these functions both for backward compatibility and for lack of analysis of all the cases.

**Comment by ebruchez** [comment]
For reference, this was done for 2023.1.
