### ISSUE TITLE
Search Controls only opens the top-level section

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5348]
Say you have a form as follows ([source](https://github.com/orbeon/orbeon-forms/files/8848600/form.txt)). If S1 is closed, and you jump to F, this opens S1. However, if S2 or S3 are closed, jumping to F doesn't open those sections. That is, it seems that the jump-to-control only opens the top-level section containing that control.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/106961/172257985-b2dbdc9c-fbc9-4e8e-8b05-7bead52029c4.png">

**Comment by ebruchez** [comment]
We already have code to dispatch events recursively to the nested sections, starting with the outer ones. We do try to dispatch events, for example:

- `|fb≡s1-section|`
- `|fb≡s2-section|`
- `|fb≡s3-section|`

However, for nested sections, we get "cannot find target" errors.

This is probably because the nested sections are dynamically creating/destroying their XBL content when they close. So just after the first dispatch, the section opens, but there hasn't been a refresh yet, and so the nested controls don't exist yet. Or something along those lines.
