### ISSUE TITLE
PDF button isn't serving a PDF when the form embedded with the JavaScript API

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5355]
[+1 from customer](https://3.basecamp.com/3600924/buckets/18345583/messages/5032320953)

**Comment by ebruchez** [comment]
The server response is:

```xml
<xxf:event-response xmlns:xxf="http://orbeon.org/oxf/xml/xforms">
    <xxf:action>
        <xxf:control-values/>
        <xxf:submission method="POST" show-progress="false" target="_blank"/>
    </xxf:action>
</xxf:event-response>
```

This is ok.

The `action` on the form is, however:

```
http://localhost:9090/orbeon/fr/orbeon/bookshelf/new
```

This is not expected. We have code, in `XHTMLBodyHandler`, which either sets this to `requestPath` or to `/xforms-server-submit` when we are embedded. But because with the JavaScript embedding we do not have the `Orbeon-Client` header passed, this is not detected. We need to use the `orbeon-embeddable` URL parameter in this case, at lest for now.

**Comment by ebruchez** [comment]
We can detect embedding fine, but then we need to figure out the URL to do the `POST`. Right now we use the `action` attribute on the `<form>`.  With Java embedding, we have URL rewriting, so that `action` points to `/orbeon-embedding/xforms-server-submit` or whatever is correct. But with JavaScript embedding, this is not the case.

**Comment by ebruchez** [comment]
The server passes to the client `xformsServerPath` and `xformsServerUploadPath`:

```scala
xformsServerPath       = rewriteResource("/xforms-server"),
xformsServerUploadPath = rewriteResource("/xforms-server/upload"),
```

Could the server similarly provide a submit path?

```scala
xformsServerSubmitPath = rewriteResource(XFormsNames.XFORMS_SERVER_SUBMIT),
```

The server passes an `action` attribute value for portlet and embedded only. Otherwise the POST is to the current page's URL. The `action` URL can depend on the URL type (action vs. resource) in the case of portlets. This seems to imply that we cannot simply add an `xformsServerSubmitPath`: we'd have to keep having the server produce the path in the response, or maybe to add two new paths:

```scala
xformsServerSubmitActionPath   = ...,
xformsServerSubmitResourcePath = ...,
```

**Comment by ebruchez** [comment]
Verified that things still work with the proxy portlet in Liferay.
