### ISSUE TITLE
Upgrade to Log4j 2.18.0

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5370]
When upgrading the version number in `build.sbt`, Log4j seems unable to load our config, and the following shows in the console.

```
2022-06-28T07:11:41,729 ERROR LoggerFactory - No valid Log4j configuration found. Skipping custom logging initialization.
property `oxf.log4j-config`: URL `oxf:/config/log4j.xml` not found (Cannot find resource: /config/log4j.xml)
property `oxf.log4j2-config`: other error while reading URL `oxf:/config/log4j2.xml` (java.net.MalformedURLException: unknown protocol: oxf)
```

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/5076071246)

**Comment by ebruchez** [comment]
In `createLog4j2XmlConfig()`, we pass a ready `URL`. However the `ConfigurationSource` now converts the `URL` to a `URI`. a `URL` is recreated later, which causes the `URL` not to use our `OXFHandler`, hence the failure.

**Comment by ebruchez** [comment]
We should probably use a more standard way to register our handler. See this [StackOverflow question](https://stackoverflow.com/questions/861500/url-to-load-resources-from-the-classpath-in-java/56088592#56088592). This only works since Java 9, which is ok for Orbeon Forms 2021.1 and newer as we require Java 11.

For Orbeon Forms versions down to 2018.2, we do support at least Java 10 or 11, so we could recommend that to users if a backport is needed to these older versions.

**Comment by ebruchez** [comment]
Log4j 2.17.1 is still current as far as vulnerabilities are concerned at this time.

**Comment by ebruchez** [comment]
I tried `java.net.spi.URLStreamHandlerProvider`, but it doesn't work. This might be because Tomcat is already running and using `URL` before loading our webapp. In addition, Tomcat sets `-Djava.protocol.handler.pkgs=org.apache.catalina.webresources`.

[This SO question](https://stackoverflow.com/questions/41696088/register-custom-urlstreamhandler-in-spring-web-application-tomcat) seems to indicate that there is no good solution. Reflection "works" but you need to add `--add-opens=...` to the startup command-line, which makes deployment more complex.

Our solution with our own `object URLFactory` was fine. It's just that log4j is now messing things up completely.

**Comment by ebruchez** [comment]
The actual fix is easy to backport to older versions of Orbeon Forms.
