### ISSUE TITLE
Don't send email if we fail to read files from persistence

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5778]
Right now, we are sending an email, just without the files that we were unable to read, which means that the email is likely to be incomplete. In cases like this, we prefer to Fail Early.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/6046331817)

**Comment by ebruchez** [comment]
This makes the test "URL generator with HTTP and 404 status code" fail, due to the new call to `checkStatusCode()`.

The test expects `oxf:url-generator` to return a document like:

```xml
<document
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:type="xs:string"
    content-type="text/html"
    status-code="404"/>
```

Behavior before the commit above, introduced with 165f33b9fb3833e5f41d9be61c22598b47ee3c1d in 2009:

- `xml` and  `html` modes: throw
- other modes: return `status-code` attribute

Behavior after the commit above:

- all modes throw

I don't know if we have cases where we use this besides the test. Maybe we need this behavior to be opt-in via configuration.

**Comment by ebruchez** [comment]
For backward compatibility, introducing a new config parameter to `oxf:url-generator` as it's the safest route.
