### ISSUE TITLE
Exception caused by tinyMceObject.render() when loading orbeon/controls

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6262]
This happens in the context of the React component test app, at least when served by IntelliJ's internal server.

- [x] check if it happens when not embedding the form using the embedding API
- [x] check if it also happens when starting the test app with `react-scripts start` (`webpack-dev-server`) (not clear as we get another error in that context, see #6259)

**Comment by obruchez** [comment]
To reproduce (with the dev console and "pause on uncaught exceptions" enabled):

1. [http://localhost:8080/orbeon/fr/orbeon/controls/new?fr-wizard-page=text-controls]
2. Click on "Utility controls"
3. Click on "Text controls"

**Comment by ebruchez** [comment]
Could this be related to #6277?

**Comment by avernet** [comment]
The error is a promise rejection that occurs as TinyMCE attempts to load a custom CSS file. It tries to load a file named `default`, which results in a 404 error. We can observe this in the Network tab. This issue is caused by the `oxf.xforms.xbl.fr.tinymce.config` setting `content_css` to `default`.
