### ISSUE TITLE
fr:grid: add enclosing element and align with repeated sections

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#635]

**Comment by ebruchez** [comment]
Notes which I sent to a user to clarify what this all was about:

In Orbeon Forms 4.8, we introduced a change in the way the data for repeated grids is represented internally (that is when the form is running). However, for backward compatibility with existing data, we kept the previous data format in the database. So there are two XML representations of the data for repeated grids:

Internally, at runtime, there is an *outer element*, so a repeated grid looks like this:

```xml
<form>
    <my-section>
        <my-city/>
        <my-repeated-grid>
            <my-repeated-grid-iteration>
                <my-name>Emma</my-name>
            </my-repeated-grid-iteration>
            <my-repeated-grid-iteration>
                <my-name>Mason</my-name>
            </my-repeated-grid-iteration>
        </my-repeated-grid>
    </my-section>
</form>
```

In the database, via the persistence API, there is currently *no outer element*, so a repeated grid looks like this:

```xml
<form>
    <my-section>
        <my-city/>
        <my-repeated-grid>
            <my-name>Emma</my-name>
        </my-repeated-grid>
        <my-repeated-grid>
            <my-name>Mason</my-name>
        </my-repeated-grid>
    </my-section>
</form>
```

There are two aspects to this migration:

1. The migration of the form definition.
2. The migration of the data.

These conversions are only necessary when there are repeated grids. In all other cases, at this time, no conversion is required.

The form definition is migrated when you load a form definition in Form Builder. It will only have an actual effect if you actually publish that form definition again. This form definition migration updates the XML data in the form definition, including repeat templates, and binds. It also changes repeated grids from:

```xml
<fr:grid repeat="true">
```

to:

```xml
<fr:grid repeat="content">
```

This means that if you upgrade Orbeon Forms, but don't upgrade/republish your form definitions, things will run as they did in the past: the internal format and external formats are the same, and there is never an "outer element".

However if you make changes to the form definition and publish it, then some conversions will take place, and the internal and external formats will differ. This is because we want Form Builder to work only on the latest format of form definitions, which enable new features, in particular.

When that is the case (that is when you have un upgrade form definition which is published and running), when Form Runner reads and writes data from and to the persistence layer, it *converts the data* back and forth.

Form Runner will only do this if the *migration metadata* is present. It is added by Form Builder when you *publish* the form definition. It looks like this:

```xml
<migration version="4.8.0">
    [{ "path": "(my-section)/(my-repeated-grid)", "iteration-name": "my-repeated-grid-iteration" }]
</migration>
```

The [exponential whitespace issue #2749](2749) was only happening when this conversion was taking place, which required:

- a form definition republished in the new format
- at least one repeated grid
- the migration metadata to be present

*BTW If you don't use Form Builder to publish, the migration information won't be there, so no migration will take place, and you run the risk of having two different data formats in your database depending on which form definitions were published by Form Builder and which weren't.*
