### ISSUE TITLE
Form Builder displays gray zone below form in some cases

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6376]
This is not clear what triggers this behavior. It seems to happen only with longer forms (?).

https://github.com/orbeon/orbeon-forms/assets/1003397/29d99cce-77a6-43ec-b5c0-83d2a132c117

**Comment by obruchez** [comment]
This happens in 2023.1.3.

**Comment by ebruchez** [comment]
I have noticed it too. It would be good to figure that one out.

**Comment by avernet** [comment]
As discussed today with @obruchez, to reproduce:

- On macOS, ensure that your scrollbars are always visible (in Settings, set "Show scroll bars" to "Always").
- Create a new form in Form Builder.
- Adjust the window height so that only the current section is visible.
- Add a section, scroll down, hover over the grid in the new section, and observe how the scrollbar "extends" when doing this.
- Scroll down to the gray area.

https://github.com/orbeon/orbeon-forms/assets/106961/500f1a81-65b5-4d3f-af95-8acc118b68f7
