### ISSUE TITLE
Dynamic Dropdown with Search: usability issues

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6597]
I noticed this after the list is open:

- the Escape key doesn't close it (regression compared with 2023.1.5)
- clicking outside the list doesn't close it (maybe not a regression)

<img width="468" alt="image" src="https://github.com/user-attachments/assets/fa564d48-9b6f-45de-b0d3-65422a4691d3">

**Comment by avernet** [comment]
Strange, I’m not seeing this on master: both pressing Esc and clicking elsewhere on the page close the dropdown. Did I misunderstand how to reproduce this? If not, do you also see this in the Controls example?

![screencast](https://github.com/user-attachments/assets/281b728f-ab85-4949-8e50-3d0fd99151da)

**Comment by avernet** [comment]
To reproduce, click at the bottom of the page below the buttons.

**Comment by avernet** [comment]
This issue is caused by https://github.com/select2/select2/issues/4939. The suggested workaround in that thread is to use CSS to extend the body to occupy 100% of the viewport height. Unsure of the potential consequences, particularly when embedding, I opted instead to register my own listener on the document element.
