### ISSUE TITLE
Lost "+" (Add another line to the repeated grid) for multiline repeats

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6622]
This regressed between 2023.1.3 and 2023.1.4, most likely with #4491.
To reproduce use http://localhost:8080/orbeon/fr/orbeon/repeated-grids/new.

✅ With 2023.1.3:

  <img width="600px" src="https://github.com/user-attachments/assets/054560a8-7730-49b3-a9b7-308103f61288">

❎ With 2023.1.4:

  <img width="600px" src="https://github.com/user-attachments/assets/0c458a34-91d2-4f6e-92f1-e3bf1dd245b4">

[+1 from customer](https://3.basecamp.com/3600924/buckets/3237397/messages/8002972055)
[+1 from customer](https://3.basecamp.com/3600924/buckets/18358270/messages/7936867625)

**Comment by ebruchez** [comment]
- when fixing #4491, I also fixed the handling of grid borders, which were inconsistent
- while doing so, I decided that having a "+" on an otherwise empty line was not elegant

We could re-add the "+", but in general it doesn't look too good. Can we figure out something better? Maybe the "+" should be in each iteration, under the menu? There should be enough space since this happens only when iterating over more than one row.

**Comment by avernet** [comment]
In WIP, restored the line header with the "+" for multiline repeats, but we're "just" missing a border with the CSS grid layout.

![image](https://github.com/user-attachments/assets/b9de8758-4244-489f-9453-7bca73fd67fe)

**Comment by avernet** [comment]
Notes regarding the last commit:

```
- Readonly: no
    - Multiple: no  ⇒ header yes
    - Multiple: yes ⇒ header yes
- Readonly: yes
    - Multiple: no  ⇒ header yes
    - Multiple: yes ⇒ header no

Take out header if readonly + multiple

Readonly: `.xforms-readonly` on the `<div>` around the `<table>`
Multiple: `.fr-repeat-multiple-rows` on the `<table>`
```
