### ISSUE TITLE
Failing constraint should default to false()

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#835]
Right now, if a `constraint` fails at runtime, it defaults to `true()`.

It seems reasonable to default instead to `false()`, because the constraint should not be ignored in cases such as:
- a programming error
- access to incorrect types (with type annotations)

**Comment by ebruchez** [comment]
Just hit the following with `required`, writing:

    $foo = 42

where control `foo` is of type `decimal`.

This makes the control required if `foo`'s value is not a decimal, and I find it a bit surprising: if it takes a specific condition to make a control required, and that condition is not met because of an error, then the control should not be required. Would this argue in favor of the `false` option above?

See also #1112. The suggested change with the empty sequence there would take care of this particular issue.

**Comment by avernet** [comment]
Instead, let's say for `required` you had:

    $foo != '42'

With this, you're saying: "if the user entered 42 in `foo` I'm good, otherwise I also need them to fill out this field". If `foo` was left empty, most likely you'd like users to fill out this field, i.e. would like the `required` to be `true`, which is the current behavior.

Going to `false` when the expression fails wouldn't achieve the "expected" result in this case. And having `$foo` evaluate to the empty sequence wouldn't work either, as `() != 42` evaluates to `false`. (If the form author had written `not($foo = 42)`, the latter would have worked, but what is the chance of a form author doing that?)

I have no solution to offer.
